export type Reel = {
  id: string;
  hook: string;
  remember: string;
  bite: string;
  tag: "TRAP" | "QUIZ" | "PROJECT" | "HEEDS" | "NOTE" | "V&V" | "DoE";
  youtubeId?: string;
  learnSlug?: string;
  quizDeck?: string;
  noteImage?: string;
};

const TAG_COLOR: Record<Reel["tag"], string> = {
  TRAP: "#EF4444",
  QUIZ: "#8B5CF6",
  PROJECT: "#06B6D4",
  HEEDS: "#F97316",
  NOTE: "#F59E0B",
  "V&V": "#22C55E",
  DoE: "#3B82F6",
};

export function reelTagColor(tag: Reel["tag"]) {
  return TAG_COLOR[tag];
}

/** Gameplay loop — verified embeddable (study-reel style background) */
export const GAMEPLAY_LOOP_ID = "ZVnjOPwW4ZA";

export const REELS_FEED: Reel[] = [
  {
    id: "r01",
    hook: "Prof FAILS you if you say this 🚫",
    remember: "Digital twin ≠ 3D CAD copy",
    bite: "Say: digital representation THROUGHOUT ITS LIFECYCLE. Virtual product. Does NOT replace testing.",
    tag: "TRAP",
    youtubeId: "9CcbYQ5QA70",
    learnSlug: "quiz-q1-digital-twin",
    quizDeck: "official",
  },
  {
    id: "r02",
    hook: "5 lifecycle stages — 10 sec challenge ⏱️",
    remember: "Design → Manufacture → Build → Test → Service",
    bite: "NOT software dev phases (Planning/Agile). Service = as-used with live sensors.",
    tag: "QUIZ",
    learnSlug: "quiz-q2-lifecycle",
    quizDeck: "official",
  },
  {
    id: "r03",
    hook: "Accuracy vs Fidelity — stop swapping them",
    remember: "Accuracy = bullseye · Fidelity = zoom level",
    bite: "Fine mesh = higher fidelity. Does NOT automatically mean more accurate.",
    tag: "TRAP",
    learnSlug: "quiz-q4-accuracy-fidelity",
    noteImage: "PHOTO-2026-04-27-12-02-20 7.jpg",
  },
  {
    id: "r04",
    hook: "THE #1 oral exam trap 🎯",
    remember: "Verification = maths RIGHT? · Validation = RIGHT maths?",
    bite: "FEA vs analytical = verification. Simulation vs wind tunnel = validation.",
    tag: "V&V",
    youtubeId: "9x9LYvErnwk",
    learnSlug: "quiz-q8-verification-validation",
    quizDeck: "vv",
  },
  {
    id: "r05",
    hook: "Calibration is NOT validation",
    remember: "Calibrate = tune knobs · Validate = check reality",
    bite: "Fit spring line = calibration. Test at new force = validation.",
    tag: "V&V",
    learnSlug: "quiz-q7-validation-calibration",
    quizDeck: "vv",
  },
  {
    id: "r06",
    hook: "Coupling ≠ connecting software",
    remember: "Coupling = physics loop · Automation = file workflow",
    bite: "HVAC: Occupancy↑ → Heat↑ → Cooling↑ → Energy↑. Interdependent.",
    tag: "QUIZ",
    youtubeId: "HftDI09LVI0",
    learnSlug: "quiz-q5-coupling",
    noteImage: "PHOTO-2026-04-27-12-02-19 8.jpg",
  },
  {
    id: "r07",
    hook: "Memorise this formula NOW 📐",
    remember: "RUL = 175200 / (f_wind × f_temp × 24)",
    bite: "f_wind=(v/5)^1.6 · f_temp=2^((T-20)/15)",
    tag: "PROJECT",
    learnSlug: "exercise-5-heeds",
  },
  {
    id: "r08",
    hook: "3 numbers = instant credibility",
    remember: "(5,20°C)=20yr · (15,35)=1.7yr · (35,65)=41 days",
    bite: "Say these without looking. Prof loves sanity checks.",
    tag: "PROJECT",
    quizDeck: "project",
  },
  {
    id: "r09",
    hook: "Wind beats temperature 3.5× 🌬️",
    remember: "Wind dominant degradation factor",
    bite: "ΔRUL wind ≈ 2466 days vs temp ≈ 695 days. Counterintuitive for RF engineers.",
    tag: "PROJECT",
    quizDeck: "project",
  },
  {
    id: "r10",
    hook: "Safe ops envelope — say this to investors",
    remember: "wind ≤12 m/s · temp ≤30°C → RUL >10 years",
    bite: "Stays INSIDE DoE bounds. Beyond 35 m/s = extrapolation trap.",
    tag: "PROJECT",
    learnSlug: "quiz-q12-extrapolation",
  },
  {
    id: "r11",
    hook: "HEEDS workflow — 6 words",
    remember: "Process → Parameters → Tagging → Study → Run → POST",
    bite: "Spring DoE study = DOE type. NOT optimization. Maps to your 40-run antenna.",
    tag: "HEEDS",
    youtubeId: "HvF_3Rok8RY",
    quizDeck: "heeds",
  },
  {
    id: "r12",
    hook: "Full factorial in 5 sec",
    remember: "4 wind × 10 temp = 40 runs",
    bite: "Cheap analytical model → full factorial OK. Same as HEEDS Ex 4 spring 2³=8.",
    tag: "DoE",
    youtubeId: "_Rgue-7KDww",
    quizDeck: "doe",
  },
  {
    id: "r13",
    hook: "Pareto CHART ≠ Pareto FRONT",
    remember: "Chart = rank factors · Front = trade-off objectives",
    bite: "Antenna wind vs temp = sensitivity ranking, not multi-objective front.",
    tag: "DoE",
    learnSlug: "notes-page-3",
    noteImage: "PHOTO-2026-04-27-12-02-19 5.jpg",
  },
  {
    id: "r14",
    hook: "4 DoE types — name them",
    remember: "Full · Fractional · Screening · Latin hypercube",
    bite: "20 factors, 30 runs → screening. 2 factors, 16 budget → full factorial.",
    tag: "DoE",
    quizDeck: "doe",
  },
  {
    id: "r15",
    hook: "PCA Step 0 is always…",
    remember: "NORMALIZE (Step 0)",
    bite: "0 Norm · 1 Covariance · 2 Eigen · 3 Order λ · 4 Matrix P · 5 Transform. UNSUPERVISED.",
    tag: "NOTE",
    youtubeId: "FgakZw6K1QQ",
    learnSlug: "notes-page-4",
    noteImage: "PHOTO-2026-04-27-12-02-18 2.jpg",
  },
  {
    id: "r16",
    hook: "Least squares — write it",
    remember: "Minimise Σ(yᵢ − f(xᵢ))²",
    bite: "Exercise 1 Hooke: slope of F vs x = k in N/m. Convert mm→m.",
    tag: "QUIZ",
    youtubeId: "_UVHneBUBW0",
    learnSlug: "quiz-q11-least-squares",
  },
  {
    id: "r17",
    hook: "Extrapolation = exam landmine 💣",
    remember: "Outside measured range = higher risk",
    bite: "Spring data to 1.5N only → predicting 5N = extrapolation. Plastic deformation possible.",
    tag: "TRAP",
    learnSlug: "quiz-q12-extrapolation",
  },
  {
    id: "r18",
    hook: "Parametric geometry in one line",
    remember: "Change one parameter → whole model + simulation updates",
    bite: "Enables DoE and as-built variations. ≠ 'just 3D CAD'.",
    tag: "QUIZ",
    learnSlug: "quiz-q3-parametric",
  },
  {
    id: "r19",
    hook: "Physics vs Empirical",
    remember: "Physics = first principles · Empirical = data/curves",
    bite: "Both matter. Your RUL = physics. Spring curve fit = empirical. ML = empirical at scale.",
    tag: "QUIZ",
    learnSlug: "quiz-q6-empirical-physics",
  },
  {
    id: "r20",
    hook: "Exercise 9 = which V&V word?",
    remember: "VALIDATION — FEA vs physical test",
    bite: "Metrics: MAC, strain error %, R². Calibrate Young's modulus if gap too big.",
    tag: "V&V",
    learnSlug: "exercise-9-correlation",
    quizDeck: "fem",
  },
  {
    id: "r21",
    hook: "FFD is NOT software architecture",
    remember: "Functional flow = real problem abstraction",
    bite: "Monitor → Compare → Adjust → Predict → Feedback. Draw for antenna tower.",
    tag: "QUIZ",
    learnSlug: "exercise-4-functional",
    noteImage: "PHOTO-2026-04-27-12-02-20 5.jpg",
  },
  {
    id: "r22",
    hook: "P-diagram centre = ?",
    remember: "Ideal response / function being controlled",
    bite: "Antenna centre: Maintain structural integrity & predict RUL. Noise = weather, tire wear analog.",
    tag: "QUIZ",
    learnSlug: "notes-page-8",
  },
  {
    id: "r23",
    hook: "Mesh convergence — 4 steps",
    remember: "Coarse → Refine → Iterate → Check",
    bite: "Analytical RUL for system DoE. FEA for local stress validation.",
    tag: "NOTE",
    learnSlug: "notes-page-5",
    noteImage: "PHOTO-2026-04-27-12-02-19 6.jpg",
  },
  {
    id: "r24",
    hook: "Monte Carlo in plain English",
    remember: "Roll dice on inputs → run model 1000×",
    bite: "Swiss cheese: failure needs all holes to line up. HEEDS Ex 5 = robustness.",
    tag: "DoE",
    youtubeId: "PD_0QjEyQJk",
    learnSlug: "notes-page-9",
  },
  {
    id: "r25",
    hook: "Your project TRL?",
    remember: "TRL 4–5 with evidence — not aspirational 9",
    bite: "Drone pipeline demonstrated (~€220K). Full fleet predictive twin not deployed yet.",
    tag: "PROJECT",
    youtubeId: "9UpMeDO0A04",
    quizDeck: "project",
  },
  {
    id: "r26",
    hook: "Pugh matrix = early concept pick",
    remember: "+ / − / S scoring vs criteria",
    bite: "Compare climber-only vs drone-only vs full twin. Twin wins on accuracy + prediction.",
    tag: "NOTE",
    quizDeck: "functional",
  },
  {
    id: "r27",
    hook: "Data matching = ?",
    remember: "Model CALIBRATION (note p.3)",
    bite: "Tune f_wind exponent 1.6 from field data. Then validate on held-out towers.",
    tag: "V&V",
    learnSlug: "notes-page-3",
  },
  {
    id: "r28",
    hook: "FEM equation — say it",
    remember: "[k]{u} = {F}",
    bite: "6 steps: Discretize · Element eq · Assembly · BCs · Solve · Postprocess. Ch31 heated rod = 1D idealisation.",
    tag: "QUIZ",
    youtubeId: "pcLg6C_WlHg",
    quizDeck: "fem",
  },
  {
    id: "r29",
    hook: "Steady vs Transient",
    remember: "Steady = snapshot · Transient = movie over time",
    bite: "Exercise 8 = transient dynamics. Your RUL model = steady system-level.",
    tag: "QUIZ",
    learnSlug: "exercise-8-dynamics",
  },
  {
    id: "r30",
    hook: "Curve fitting ≠ validation",
    remember: "Fit on Monday · Validate on Tuesday",
    bite: "Quiz Q10: generating curve close to data. Still need independent test.",
    tag: "TRAP",
    learnSlug: "quiz-q10-curve-fitting",
  },
  {
    id: "r31",
    hook: "Idealisation ≠ bad model",
    remember: "Simplify wisely — keep important physics",
    bite: "3D → 2D slice → 1D rod. PCB: simplify board, keep chip hotspot.",
    tag: "QUIZ",
    learnSlug: "quiz-q9-idealisation",
  },
  {
    id: "r32",
    hook: "Agile vs Waterfall — one line",
    remember: "Agile = iterative delivery + customer collab",
    bite: "Software cycle: Planning→Analysis→Design→Implementation→Testing→Maintenance. V&V in Testing.",
    tag: "NOTE",
    learnSlug: "notes-page-5",
  },
  {
    id: "r33",
    hook: "Injection molding DoE example",
    remember: "Inputs: temp, pressure, cooling",
    bite: "Outputs: weight, deviation, surface, cycle time. Prof's go-to besides antenna.",
    tag: "DoE",
    learnSlug: "notes-page-3",
  },
  {
    id: "r34",
    hook: "AIAA Exercise 2 — company value",
    remember: "Predictive maintenance saves outages + climber cost",
    bite: "Drone geometry + RUL physics = your exam story. €220K industrial context.",
    tag: "PROJECT",
    youtubeId: "ObGhB9CCHP8",
    learnSlug: "exercise-2-aiaa",
  },
  {
    id: "r35",
    hook: "Exercise 11 = your project cousin",
    remember: "Bearing prognosis: sensors → health index → RUL",
    bite: "Physics RUL (yours) vs data-driven ML. Both answer: when will it fail?",
    tag: "PROJECT",
    learnSlug: "exercise-11-prognosis",
  },
  {
    id: "r36",
    hook: "Process automation 4 pillars",
    remember: "CAD · Simulation · DoE/Optim · Data/workflow",
    bite: "HEEDS+iSight = MDO stack. Your Python notebook = manual process automation.",
    tag: "HEEDS",
    youtubeId: "SwgtZp4Jcjs",
    quizDeck: "heeds",
  },
  {
    id: "r37",
    hook: "Global vs local minimum",
    remember: "Global = best in whole space · Local = neighbourhood best",
    bite: "Optimization trap. Pareto front = conflicting objectives trade-off curve.",
    tag: "DoE",
    quizDeck: "doe",
  },
  {
    id: "r38",
    hook: "Motorcycle FFD feedback loop",
    remember: "Predict → Adjust throttle → Monitor again",
    bite: "Same pattern as antenna: Monitor RUL → Schedule maintenance → Re-scan.",
    tag: "NOTE",
    learnSlug: "notes-page-6-7",
    noteImage: "PHOTO-2026-04-27-12-02-19 7.jpg",
  },
  {
    id: "r39",
    hook: "Oral exam: DT definition verbatim",
    remember: '"…throughout its lifecycle — the virtual product"',
    bite: "30 seconds. Record yourself tonight. Must include does NOT replace testing.",
    tag: "TRAP",
    learnSlug: "quiz-q1-digital-twin",
    quizDeck: "official",
  },
  {
    id: "r40",
    hook: "90% of Q&A is THEORY",
    remember: "She asks beyond your slides",
    bite: "Scroll these reels instead of Instagram. Then hit Quiz deck for score.",
    tag: "TRAP",
    quizDeck: "official",
  },
  {
    id: "r41",
    hook: "Exercise 7 — Simcenter thermal",
    remember: "PCB + chip hotspot → temperature field",
    bite: "Workflow: CAD→mesh→materials→BCs→solve→post. One V + one V action.",
    tag: "QUIZ",
    youtubeId: "cHThndE20oI",
    learnSlug: "exercise-7-thermal",
  },
  {
    id: "r42",
    hook: "Surrogate model = ?",
    remember: "Fast approximation of expensive simulation",
    bite: "Wing AI: geometry in → lift/drag out. Your RUL formula = medium-fidelity surrogate.",
    tag: "NOTE",
    learnSlug: "notes-page-4",
  },
  {
    id: "r43",
    hook: "FMEA columns — quick recall",
    remember: "Mode · Effect · Severity · Cause · Detection · RPN",
    bite: "One row: wind fatigue structural failure on antenna. Swiss cheese = layered defences.",
    tag: "NOTE",
    quizDeck: "functional",
  },
  {
    id: "r44",
    hook: "MATLAB optimproblem — 4 words",
    remember: "optimproblem · optimvar · optimconstr · optimexpr",
    bite: "Exercise 6. Maximise RUL s.t. wind≤12, temp≤30.",
    tag: "HEEDS",
    learnSlug: "exercise-6-matlab",
  },
  {
    id: "r45",
    hook: "You scrolled productively 🧠",
    remember: "Open Quiz → Mixed drill → 85%+ target",
    bite: "Tap Learn for deep dive. Project tab for SRH PPT. You didn't waste this scroll.",
    tag: "TRAP",
    quizDeck: "mix",
  },
];

export const REELS_TOTAL = REELS_FEED.length;

export function getReel(id: string): Reel | undefined {
  return REELS_FEED.find((r) => r.id === id);
}
