import type { QuizQuestion } from "./types";

function q(
  id: string,
  deck: string,
  topic: string,
  question: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string,
  source: string
): QuizQuestion {
  return { id, deck, topic, question, options, correctIndex, explanation, source };
}

export const QUIZ_BANK: QuizQuestion[] = [
  // ─── DEEP STUDY — exercises & notes plain-language checks ─────
  q("deep-01", "deep", "Ex 1", "In Exercise 1, you find spring constant k by:",
    ["Counting mesh elements", "Slope of Force vs Displacement line (least squares)", "Running HEEDS POST", "Drawing a P-diagram"],
    1, "Plot F vs x, fit line, slope = k in N/m after mm→m conversion.", "Exercise 1"),
  q("deep-02", "deep", "Ex 2", "Exercise 2 AIAA paper — your company value answer should mention:",
    ["Only video games", "Predictive maintenance reducing outages and inspection cost", "Deleting all physical tests", "Only CAD modelling"],
    1, "Drone + RUL predictive maintenance is your project story.", "Exercise 2"),
  q("deep-03", "deep", "Ex 4", "FFD for antenna tower includes feedback from prediction back to:",
    ["Only PowerPoint", "Monitor step (closed loop)", "Only mesh refinement", "Exam grading"],
    1, "Monitor→Compare→Adjust→Predict→Feedback.", "Exercise 4"),
  q("deep-04", "deep", "Ex 5", "HEEDS coil spring study type must be:",
    ["Optimization only", "DOE — not optimisation", "CAD import only", "PCA"],
    1, "Example 4 is DoE; antenna maps same workflow.", "Exercise 5"),
  q("deep-05", "deep", "Ex 7", "Simcenter Exercise 7 finds hotspot temperature on:",
    ["Coil spring", "PCB with chip", "Motorcycle tire", "Logistics truck"],
    1, "Thermal PCB tutorial.", "Exercise 7"),
  q("deep-06", "deep", "Ex 8", "Transient analysis differs from steady-state because:",
    ["It uses no mesh", "Output changes over time (impact, vibration pulse)", "It is only 1D", "It replaces validation"],
    1, "Time history vs single snapshot.", "Exercise 8"),
  q("deep-07", "deep", "Ex 9", "Exercise 9 correlation is an example of:",
    ["Verification only", "Model validation vs physical test", "Pugh matrix", "Agile sprint"],
    1, "FEA vs test = validation.", "Exercise 9"),
  q("deep-08", "deep", "Ex 11", "Bearing prognosis and your antenna RUL both answer:",
    ["What colour is the part?", "How much useful life remains?", "How to mesh PCB?", "What is PCA step 0?"],
    1, "Prognostics = RUL forecasting.", "Exercise 11"),
  q("deep-09", "deep", "Note p.3", "Four DoE types in your notes include:",
    ["Only Monte Carlo", "Full factorial, fractional factorial, screening, Latin hypercube", "Only optimisation", "Only CAD"],
    1, "Memorise all four names.", "Note p.3"),
  q("deep-10", "deep", "Note p.4", "PCA Step 0 is always:",
    ["Skip data", "Normalize the data", "Run HEEDS", "Delete outliers blindly"],
    1, "Six steps 0–5; step 0 = normalize.", "Note p.4"),
  q("deep-11", "deep", "Note p.5", "Software dev cycle — verification happens in:",
    ["Planning", "Testing & integration phase", "Only maintenance", "Never"],
    1, "Six stages from note p.5.", "Note p.5"),
  q("deep-12", "deep", "Note p.7", "HVAC coupling chain starts with:",
    ["Energy consumption", "Occupancy increase", "Only CFD mesh", "PCA eigenvalues"],
    1, "Occupancy→Heat→Cooling→Energy.", "Note p.7"),
  q("deep-13", "deep", "Note p.8", "P-diagram NOISE factors for traction include:",
    ["Only throttle", "Road condition, tire wear, temperature", "Only software version", "Only spring k"],
    1, "Noise = uncontrolled variation.", "Note p.8"),
  q("deep-14", "deep", "Note p.9", "Swiss cheese model means:",
    ["Cheese manufacturing DoE", "Multiple defence layers — failure needs all holes to align", "Only Agile", "Only mesh"],
    1, "Links to Monte Carlo risk sampling.", "Note p.9"),
  q("deep-15", "deep", "Plain", "Simplest digital twin definition for oral exam:",
    ["A 3D photo", "Computer model of real product through whole lifecycle", "Only sensors", "Only Excel"],
    1, "Must say lifecycle.", "Learn guide · Q1"),

  // ─── OFFICIAL QUIZ Q1–12 ─────────────────────────────────────
  q("official-01", "official", "Q1", "What is Prof. Nasti's correct definition of a digital twin?",
    ["A 3D CAD copy of a physical product", "The digital representation of a physical product throughout its lifecycle", "A real-time sensor dashboard only", "A cloud backup of manufacturing files"],
    1, "Must include 'throughout its lifecycle' — not just CAD or sensors.", "Quiz Q1"),
  q("official-02", "official", "Q1", "Does a digital twin replace experimental testing?",
    ["Yes — simulation is always sufficient", "No — simulation de-risks but testing is still required", "Only for aerospace", "Only after TRL 9"],
    1, "Prof fails anyone who says DT replaces testing.", "Quiz Q1"),
  q("official-03", "official", "Q1", "What is at the core of every digital twin per Prof. Nasti?",
    ["A PDF report", "A fully coupled multi-disciplinary parametric simulation model", "A blockchain ledger", "A marketing brochure"],
    1, "Coupled + parametric simulation is the core.", "Quiz Q1"),
  q("official-04", "official", "Q2", "Which is the CORRECT order of product lifecycle stages?",
    ["Service → Design → Manufacture → Test → Assembly", "Design & Analysis → Manufacture → Build & Assembly → Experimental Testing → Service", "Planning → Analysis → Design → Implementation → Testing", "Concept → Prototype → Production → Retirement"],
    1, "Five stages in this exact order — not software dev cycle.", "Quiz Q2"),
  q("official-05", "official", "Q2", "AIAA 'as-used' stage maps to which lifecycle stage?",
    ["Design & Analysis", "Manufacture", "Build & Assembly", "Service"],
    3, "As-used = operation with live sensor data = Service phase.", "Quiz Q2 · AIAA"),
  q("official-06", "official", "Q3", "Why is parametric geometry important for digital twins?",
    ["It makes prettier renders", "One master model can simulate as-designed AND as-manufactured by changing parameters", "It eliminates the need for meshing", "It replaces DoE"],
    1, "Parameters drive geometry AND downstream simulation automatically.", "Quiz Q3"),
  q("official-07", "official", "Q3", "Parametric geometry modelling means:",
    ["Static STL export only", "Design variables drive geometry and linked simulation automatically", "Only 2D sketches", "Manual remeshing for every design change"],
    1, "Parametric ≠ 'just 3D CAD'.", "Quiz Q3"),
  q("official-08", "official", "Q4", "Model ACCURACY means:",
    ["Level of detail in the mesh", "How close predictions are to reality", "Number of CPU cores used", "File size of the CAD model"],
    1, "Detail level = fidelity, not accuracy — common trap.", "Quiz Q4"),
  q("official-09", "official", "Q4", "Model FIDELITY means:",
    ["How close predictions are to reality", "Level of detail/realism in mirroring physical assets", "Software verification status", "Cost of the simulation license"],
    1, "Fidelity = detail; Accuracy = closeness to reality.", "Quiz Q4 · Note p.1"),
  q("official-10", "official", "Q5", "Model COUPLING means:",
    ["Connecting two software tools with a script", "Solving interdependent models iteratively because outputs feed inputs", "Using the same mesh for CFD and FEA", "Running simulations in parallel on a cluster"],
    1, "Coupling = physics interdependence, not just process automation.", "Quiz Q5"),
  q("official-11", "official", "Q5", "In the HVAC smart building example, occupancy increase leads to:",
    ["Lower energy use directly", "Higher heat generation → higher cooling demand → higher energy", "Only airflow change with no thermal effect", "Decoupled independent models"],
    1, "Four coupled models in a causal chain.", "Quiz Q5 · Note p.7"),
  q("official-12", "official", "Q6", "An EMPIRICAL model is built from:",
    ["First principles physics only", "Real-world observations and statistical methods on data", "Guesswork without data", "CAD geometry alone"],
    1, "Empirical = data-driven; physics-based = first principles.", "Quiz Q6"),
  q("official-13", "official", "Q6", "Physics-based vs empirical — which is correct?",
    ["Empirical is always wrong", "Both matter in practice; physics models still need validation", "Physics models never need data", "They are identical concepts"],
    1, "Prof: both matter; even physics models need experimental validation.", "Quiz Q6"),
  q("official-14", "official", "Q7", "MODEL VALIDATION checks:",
    ["Whether code implements maths correctly", "Whether model predictions match real-world behaviour — 'right maths?'", "Whether the mesh has tetrahedral elements", "Whether the CAD is parametric"],
    1, "Validation = right maths vs reality.", "Quiz Q7"),
  q("official-15", "official", "Q7", "MODEL CALIBRATION (data matching) is:",
    ["The same as validation", "Tuning internal parameters to match experimental data", "Deleting bad test data", "Running Monte Carlo only"],
    1, "Calibration tunes parameters; validation assesses agreement with reality.", "Quiz Q7"),
  q("official-16", "official", "Q8", "VERIFICATION asks:",
    ["Have I done the right maths?", "Have I done the maths right?", "Is the product profitable?", "Is the mesh converged?"],
    1, "Verification = maths right; Validation = right maths.", "Quiz Q8"),
  q("official-17", "official", "Q8", "Comparing CFD results to a wind tunnel test is:",
    ["Verification", "Validation", "Calibration only", "Neither"],
    1, "CFD vs experiment = validation.", "Quiz Q8"),
  q("official-18", "official", "Q8", "Comparing FEA code output to an analytical beam solution is:",
    ["Validation", "Verification", "Marketing", "Calibration"],
    1, "Code vs analytical = verification.", "Quiz Q8"),
  q("official-19", "official", "Q9", "Geometry IDEALISATION means:",
    ["Making the model less accurate on purpose", "Simplifying geometry while preserving physics of interest", "Deleting the CAD model", "Using only 3D always"],
    1, "Idealisation = engineering judgement, not 'bad model'.", "Quiz Q9"),
  q("official-20", "official", "Q9", "Valid geometry idealisation levels include:",
    ["Only full 3D always", "Simplified 3D, 2D slice, or 1D — synced with master CAD", "Disconnected sketches", "Paper drawings only"],
    1, "Three levels from notes; must stay synced with master model.", "Quiz Q9"),
  q("official-21", "official", "Q10", "CURVE FITTING is:",
    ["Model validation on new data", "Generating a curve close to experimental data points", "Mesh refinement", "Process automation in HEEDS"],
    1, "Fitting creates empirical model; validating tests on independent data.", "Quiz Q10"),
  q("official-22", "official", "Q11", "Least squares minimises:",
    ["The number of data points", "Σ(yᵢ − f(xᵢ))² — sum of squared residuals", "The mesh element count", "The CAD file size"],
    1, "Core formula Prof expects on exam.", "Quiz Q11 · Note p.4"),
  q("official-23", "official", "Q12", "EXTRAPOLATION means:",
    ["Prediction within measured data range", "Prediction outside the range of measured/calibrated data — higher risk", "Interpolation with splines", "Mesh convergence check"],
    1, "Extrapolation = outside bounds; higher uncertainty.", "Quiz Q12"),
  q("official-24", "official", "Q12", "For Hooke's law spring data only to 1.5 N, predicting at 5 N is:",
    ["Safe interpolation", "Extrapolation with higher uncertainty", "Verification", "Validation"],
    1, "Beyond data range = extrapolation; linear assumption may fail.", "Quiz Q12 · Exercise 1"),

  // ─── V&V TRAPS ───────────────────────────────────────────────
  q("vv-01", "vv", "Traps", "Calibration can replace validation.",
    ["True — once calibrated, model is validated", "False — calibration tunes parameters; validation needs independent check", "True only for CFD", "Depends on mesh size"],
    1, "Sequence: may calibrate THEN validate — calibration ≠ validation.", "Quiz Q7"),
  q("vv-02", "vv", "Traps", "Curve fitting completed on training data proves the model is validated.",
    ["True", "False — fitting is calibration; validation needs independent data", "True if R² > 0.9", "Only false for nonlinear models"],
    1, "Fitting ≠ validation — classic Prof trap.", "Quiz Q10"),
  q("vv-03", "vv", "Traps", "Exercise 9 (FEA vs test correlation) is primarily:",
    ["Verification", "Validation", "Process automation", "DoE screening"],
    1, "Compare simulation to physical test = validation.", "Exercise 9"),
  q("vv-04", "vv", "Traps", "d = 35.0 (±0.1) mm represents:",
    ["Software bug tolerance", "Manufacturing/measurement uncertainty", "Mesh size", "Convergence criterion"],
    1, "Links to ASME PTC 19.1 test uncertainty.", "Quiz Q4"),
  q("vv-05", "vv", "Traps", "Sanity checks on RUL anchor points (5m/s, 20°C) are:",
    ["Validation against field data", "Verification that implementation/math is consistent", "Calibration", "Extrapolation"],
    1, "Known-point checks = verification of implementation.", "Project · V&V"),
  q("vv-06", "vv", "Traps", "Comparing two different CFD codes against each other is:",
    ["Always validation", "Context-dependent — neither alone proves validation", "Always verification", "Calibration"],
    1, "Prof nuance: context matters for code-to-code comparison.", "Quiz Q8"),
  q("vv-07", "vv", "Traps", "Data matching in your notes means:",
    ["Pugh matrix scoring", "Model calibration to experimental data", "Mesh generation", "Agile sprint planning"],
    1, "Data matching = calibration (note p.3).", "Note p.3"),
  q("vv-08", "vv", "Traps", "V&V happens in which software development phase?",
    ["Planning only", "Testing & integration", "Maintenance only", "Never in simulation"],
    1, "Six-phase dev cycle from note p.5.", "Note p.5"),
  q("vv-09", "vv", "Traps", "Validation aims for:",
    ["Zero error always", "Acceptable delta vs reality (may be subjective)", "Fastest runtime", "Largest mesh"],
    1, "Validation = acceptable agreement; verification = zero implementation error.", "Quiz Q7–8"),
  q("vv-10", "vv", "Traps", "Which comes first in a rigorous workflow?",
    ["Validate then calibrate", "Often calibrate parameters then validate on independent data", "Skip both if mesh is fine", "Only verify in production"],
    1, "Calibrate on training data, validate on held-out/test data.", "Quiz Q7"),

  // ─── DOE · OPTIMIZATION ────────────────────────────────────────
  q("doe-01", "doe", "DoE", "Design of Experiments (DoE) is used to:",
    ["Replace all simulation", "Explore design space and understand input sensitivity on outputs", "Only optimise one variable", "Eliminate validation"],
    1, "DoE = structured exploration of design space.", "Lecture 102–114"),
  q("doe-02", "doe", "DoE", "Full factorial 2³ means:",
    ["2 runs total", "8 runs — all combinations of 3 factors at 2 levels each", "3 runs", "27 runs"],
    1, "2³ = 8 combinations (HEEDS spring example).", "HEEDS Ex 4"),
  q("doe-03", "doe", "DoE", "Your antenna DoE uses:",
    ["2³ fractional factorial", "4×10 full factorial = 40 runs", "Latin hypercube only", "Single baseline run"],
    1, "4 wind × 10 temp = 40 design points.", "Project"),
  q("doe-04", "doe", "Pareto", "A Pareto CHART ranks:",
    ["Conflicting objectives on a front", "Relative impact of factors on an output", "Mesh quality elements", "Software licenses by cost"],
    1, "Pareto chart ≠ Pareto front.", "Note p.3"),
  q("doe-05", "doe", "Pareto", "A Pareto FRONT shows:",
    ["Factor ranking bars", "Optimal trade-off between conflicting objectives", "Mesh convergence", "CAD feature tree"],
    1, "Front = multi-objective trade-off curve.", "Lecture · Day 2"),
  q("doe-06", "doe", "Sensitivity", "Your antenna sensitivity analysis shows wind impact is:",
    ["Equal to temperature", "Approximately 3.5× temperature impact on RUL", "Less than temperature", "Zero"],
    1, "ΔRUL wind ≈ 2466 days vs temp ≈ 695 days.", "Project notebook"),
  q("doe-07", "doe", "Monte Carlo", "Monte Carlo simulation uses:",
    ["Deterministic single values only", "Random sampling from input probability distributions", "Only CAD parameters", "Manual guesswork"],
    1, "Stochastic inputs → many deterministic runs.", "Lecture 117–119"),
  q("doe-08", "doe", "Robust", "Robust design means:",
    ["Highest fidelity mesh always", "Low sensitivity of outputs to input variation", "No uncertainty", "Fastest runtime only"],
    1, "Robust = insensitive to input scatter.", "HEEDS Ex 5"),
  q("doe-09", "doe", "UQ", "Root Sum Square (RSS) combines:",
    ["Mesh sizes", "Independent uncertainty contributions", "CAD layers", "Agile sprints"],
    1, "RSS propagates x₁±δx₁ uncertainties.", "Note p.3"),
  q("doe-10", "doe", "Optimisation", "Design optimisation differs from DoE because:",
    ["DoE explores; optimisation searches for best design given objectives/constraints", "They are identical", "DoE always uses 2 factors", "Optimisation never uses simulation"],
    0, "DoE = explore sensitivity; optimisation = find optimum.", "Lecture 108"),
  q("doe-11", "doe", "Types", "Screening DoE is used when:",
    ["You have 2 factors only", "Many factors, few runs — identify important ones", "Mesh is converged", "Only one simulation exists"],
    1, "Screening = many factors, budget-limited.", "Lecture 104"),
  q("doe-12", "doe", "Injection", "In injection molding DoE from notes, inputs include:",
    ["Only part colour", "Temperature, injection pressure, cooling time", "Only operator name", "Only mesh type"],
    1, "Classic three-factor example from note p.3.", "Note p.3"),

  // ─── HEEDS ─────────────────────────────────────────────────────
  q("heeds-01", "heeds", "Workflow", "HEEDS workflow order is:",
    ["Study → Run → Process → POST", "Process → Parameters → Tagging → Study → Run → POST", "POST → Study → Process", "Tagging → CAD → Mesh only"],
    1, "Memorise this sequence for oral exam.", "HEEDS Guide"),
  q("heeds-02", "heeds", "Workflow", "Process Automation in HEEDS means:",
    ["Writing PowerPoint slides", "Linking executables and automating file-based data transfer between tools", "Only meshing", "Deleting old results"],
    1, "Process automation = integrated design systems.", "Lecture · Note p.5"),
  q("heeds-03", "heeds", "Spring DoE", "HEEDS Coil Spring Example 4 uses study type:",
    ["Optimization only", "DOE — Screening/Response Surface (NOT optimization)", "Reliability only", "Taguchi only"],
    1, "DoE study for spring — maps to antenna factorial.", "HEEDS Ex 4"),
  q("heeds-04", "heeds", "Mapping", "In antenna↔spring mapping, wind_ms maps to:",
    ["deflection response", "coil_diam input variable", "POST plot type", "mesh size"],
    1, "Inputs: coil_diam ↔ wind_ms; outputs: deflection ↔ rul_days.", "Exercise 5"),
  q("heeds-05", "heeds", "Tools", "HEEDS and iSight are used for:",
    ["CAD modelling only", "Multidisciplinary design exploration and process automation", "Word processing", "Drone photogrammetry only"],
    1, "Siemens/Simulia MDO stack.", "Note p.5"),
  q("heeds-06", "heeds", "Tagging", "Tagging in HEEDS connects:",
    ["Only PowerPoint shapes", "Variables/responses to specific lines in input/output files", "Only mesh nodes", "Only email alerts"],
    1, "Tagging = parse files for parametric links.", "HEEDS Guide"),
  q("heeds-07", "heeds", "Studies", "HEEDS Example 5 focuses on:",
    ["Curve fitting only", "Robustness & Reliability (Monte Carlo style)", "Truss animation only", "CAD import"],
    1, "Links to Monte Carlo lecture content.", "HEEDS Ex 5"),
  q("heeds-08", "heeds", "Studies", "HEEDS Example 6 demonstrates:",
    ["1D rod FEA", "Multi-objective optimisation / Pareto front", "Hooke's law only", "PCA"],
    1, "Multi-objective Pareto in POST.", "HEEDS Ex 6"),
  q("heeds-09", "heeds", "Trap", "Coupling in simulation is the same as process automation.",
    ["True — identical concepts", "False — coupling is physics interdependence; automation is software workflow", "True only in HEEDS", "False — automation is always harder"],
    1, "#1 confusion trap from Day 1–2.", "Quiz Q5 · Day 2"),
  q("heeds-10", "heeds", "Integrated", "Integrated design systems four pillars include:",
    ["Only PowerPoint", "CAD, simulation tools, DoE/optimisation, data management", "Only social media", "Only manual spreadsheets"],
    1, "Four pillars from lecture.", "Day 2"),

  // ─── FUNCTIONAL · FMEA · PUGH ──────────────────────────────────
  q("functional-01", "functional", "FFD", "Functional flow diagrams (FFD) are:",
    ["Software architecture diagrams", "Abstraction of real problem functionality — NOT software architecture", "Mesh topology plots", "Financial charts"],
    1, "Prof trap: FFD ≠ software arch.", "Exercise 4"),
  q("functional-02", "functional", "P-diagram", "P-diagram centre element is:",
    ["A mesh node", "Ideal response / function being controlled", "Software license key", "Monte Carlo seed"],
    1, "Centre = ideal response; inputs, noise, controls around it.", "Exercise 4 · Note p.8"),
  q("functional-03", "functional", "P-diagram", "In rear wheel traction P-diagram, NOISE factors include:",
    ["Only throttle position", "Road condition, tire wear, temperature", "Only software version", "Only mesh quality"],
    1, "Noise = uncontrolled variation.", "Note p.8"),
  q("functional-04", "functional", "Antenna", "Your antenna P-diagram centre function is:",
    ["Maximise data rate only", "Maintain structural integrity & predict RUL", "Minimise CAD file size", "Eliminate all wind"],
    1, "Centre from curriculum Exercise 4 mapping.", "Exercise 4"),
  q("functional-05", "functional", "Pugh", "Pugh matrix is used for:",
    ["Mesh convergence", "Early conceptual design — comparing alternatives with +/−/S scores", "CFD turbulence modelling", "JWT authentication"],
    1, "Pugh = concept selection tool.", "Day 2"),
  q("functional-06", "functional", "FMEA", "FMEA stands for and is used to:",
    ["Fast Mesh Element Analysis", "Failure Mode & Effects Analysis — prioritise failure risks", "Finite Model Element Assembly", "Full Monte Carlo Estimation"],
    1, "Risk prioritisation tool from note p.5.", "Note p.5"),
  q("functional-07", "functional", "Motorcycle", "Motorcycle traction FFD includes feedback from:",
    ["Only CAD", "Prediction → adjust outputs (throttle, fueling) → monitor again", "No feedback loops", "Only POST in HEEDS"],
    1, "Closed-loop functional flow from note p.6–7.", "Note p.6"),
  q("functional-08", "functional", "Context", "Context diagram shows:",
    ["Internal FEA equations", "System scope and boundaries vs external actors", "Only colour legend", "Monte Carlo histogram"],
    1, "Scope/boundary diagram for Exercise 4.", "Exercise 4"),

  // ─── FEM · SIMCENTER ───────────────────────────────────────────
  q("fem-01", "fem", "FEM", "FEM solves problems by:",
    ["Ignoring discretization", "Dividing domain into elements, assembling [k]{u}={F}", "Only analytical integration", "Only Monte Carlo"],
    1, "Core FEM equation from Ch.31.", "FEM Ch.31"),
  q("fem-02", "fem", "Mesh", "Mesh convergence study steps include:",
    ["One coarse mesh only", "Coarse → refine → iterate → check convergence", "Skip refinement", "Only change material"],
    1, "Four steps from note p.5.", "Note p.5"),
  q("fem-03", "fem", "Exercise 7", "Simcenter Exercise 7 models:",
    ["Antenna RUL only", "Thermal PCB with chip hotspot", "Coil spring only", "Logistics routing"],
    1, "Thermal FEA tutorial.", "Exercise 7"),
  q("fem-04", "fem", "Exercise 8", "Exercise 8 Response Dynamics covers:",
    ["Steady heated rod only", "Transient dynamic event analysis", "Pugh matrix only", "HEEDS tagging only"],
    1, "Transient vs steady-state distinction.", "Exercise 8"),
  q("fem-05", "fem", "Idealisation", "Heated rod in FEM Ch.31 is a deliberate:",
    ["3D full model always", "1D geometry idealisation", "Monte Carlo study", "Pugh analysis"],
    1, "1D rod = idealisation example.", "Quiz Q9 · Ch.31"),
  q("fem-06", "fem", "Tools", "LS-Dyna is primarily associated with:",
    ["Spreadsheets", "Contact / highly nonlinear dynamics", "Word processing", "PCA"],
    1, "Toolchain from note p.5.", "Note p.5"),
  q("fem-07", "fem", "Antenna", "For antenna project, analytical RUL is sufficient for:",
    ["Local stress concentrations always", "System-level DoE; FEA needed for local stress validation", "Never — always skip simulation", "Only marketing"],
    1, "Breadth vs depth exam answer.", "Day 2 · Day 3"),
  q("fem-08", "fem", "Simsolid", "Simsolid is notable for:",
    ["Requiring finest tet mesh", "Mesh-free simulation approach", "Only 1D rods", "Only DoE"],
    1, "Mesh-free tool from notes.", "Note p.5"),

  // ─── ML · PCA ──────────────────────────────────────────────────
  q("ml-01", "ml-pca", "PCA", "PCA Step 0 is:",
    ["Compute eigenvalues", "NORMALIZE the data", "Run HEEDS", "Mesh the CAD"],
    1, "Six steps 0–5 from note p.4.", "Note p.4"),
  q("ml-02", "ml-pca", "PCA", "PCA is:",
    ["Supervised classification only", "Unsupervised dimensionality reduction", "CFD turbulence model", "Mesh refinement"],
    1, "Unsupervised — no labels needed.", "Note p.4"),
  q("ml-03", "ml-pca", "PCA", "In covariance matrix, diagonal elements represent:",
    ["Eigenvectors", "Variance of each feature", "Mesh size", "Wind speed"],
    1, "Diagonal = variance; off-diagonal → 0 after decorrelation.", "Note p.4"),
  q("ml-04", "ml-pca", "Surrogate", "A surrogate model is:",
    ["Always higher fidelity than FEA", "Fast approximation of expensive high-fidelity simulation data", "Only empirical with no data", "Only CAD"],
    1, "Surrogate = speed vs fidelity trade-off.", "Note p.4"),
  q("ml-05", "ml-pca", "ML", "ML could replace your RUL formula if:",
    ["Never — physics always forbidden", "Enough FEA/field data exists — but loses interpretability; needs validation", "You have no data", "Mesh is coarse"],
    1, "Exercise 10 nuance — trade-off.", "Exercise 10"),
  q("ml-06", "ml-pca", "Centrifuge", "In centrifuge PCA example, PCA1 often represents:",
    ["Only bearing serial number", "Overall vibration energy", "Operator name", "Mesh count"],
    1, "Feature extraction interpretation.", "Lecture ML slides"),
  q("ml-07", "ml-pca", "Prognostics", "Physics-based RUL vs data-driven ML prognostics:",
    ["Identical", "Physics = interpretable laws; ML = patterns from data — both need validation", "ML always better", "Physics needs no data"],
    1, "Day 3 prognostics comparison.", "Exercise 11"),

  // ─── PROJECT ───────────────────────────────────────────────────
  q("project-01", "project", "Formula", "RUL (days) formula is:",
    ["175200 × f_wind × f_temp × 24", "175200 / (f_wind × f_temp × 24)", "f_wind + f_temp only", "365 × wind only"],
    1, "Must memorise exactly.", "Notebook"),
  q("project-02", "project", "Formula", "f_wind(v) =",
    ["(v/5)^1.6", "2^((v-20)/15)", "v × 5", "v² only"],
    0, "Wind fatigue scaling exponent 1.6.", "Notebook"),
  q("project-03", "project", "Formula", "f_temp(T) =",
    ["(T/5)^1.6", "2^((T-20)/15)", "T - 20 only", "T²"],
    1, "Arrhenius — doubles every 15°C.", "Notebook"),
  q("project-04", "project", "Numbers", "RUL at 5 m/s, 20°C is approximately:",
    ["41 days", "7300 days (~20 years)", "365 days", "175200 days"],
    1, "Sanity check #1.", "Notebook"),
  q("project-05", "project", "Numbers", "RUL at 35 m/s, 65°C is approximately:",
    ["20 years", "41 days", "7300 days", "10 years"],
    1, "Sanity check #2 — harsh conditions.", "Notebook"),
  q("project-06", "project", "Envelope", "Recommended safe operating region:",
    ["Wind ≤35 m/s, any temperature", "Wind ≤12 m/s, temp ≤30°C → RUL >10 years", "No limits needed", "Temp only matters"],
    1, "Operating envelope slide.", "Notebook"),
  q("project-07", "project", "TRL", "Antenna project is approximately TRL:",
    ["1 — basic principles only", "4–5 — validated in lab/relevant environment, not fleet-deployed", "9 — fully deployed everywhere", "0"],
    1, "Justify with evidence, not aspiration.", "Day 2"),
  q("project-08", "project", "Industrial", "Industrial context includes:",
    ["Fictional example only", "Drone 2D→3D pipeline, USA telecom client ≈€220K", "Only classroom", "Only HEEDS spring"],
    1, "Real industrial breadth for exam.", "Notebook intro"),
  q("project-09", "project", "Creative", "Your creative contribution is:",
    ["Copying HEEDS manual only", "Extending drone geometry pipeline with original physics RUL + full DoE", "Only watching videos", "Only reading AIAA"],
    1, "Creativity criterion on rubric.", "Exam Guidelines"),
  q("project-10", "project", "Extrapolation", "Predicting RUL at 40 m/s when DoE max is 35 m/s is:",
    ["Safe interpolation", "Extrapolation — higher uncertainty", "Verification", "Calibration"],
    1, "Stay inside envelope for recommendations.", "Quiz Q12 · Project"),

  // ─── NOTES TRAPS ───────────────────────────────────────────────
  q("notes-01", "notes", "Agile", "Agile project management emphasises:",
    ["Waterfall-only sequential delivery", "Iterative delivery, customer collaboration, flexibility", "No testing", "No simulation"],
    1, "Contrast to waterfall from note p.5.", "Note p.5"),
  q("notes-02", "notes", "Dev cycle", "Software development cycle order includes Testing where:",
    ["Verification occurs", "Only marketing happens", "CAD is deleted", "DoE is forbidden"],
    0, "Planning→Analysis→Design→Implementation→Testing→Maintenance.", "Note p.5"),
  q("notes-03", "notes", "Swiss cheese", "Swiss cheese model in Monte Carlo context:",
    ["Layers of defences — failures align only if holes line up", "Cheese manufacturing DoE", "Mesh layering", "CAD feature tree"],
    0, "Risk/probability mental model.", "Lecture · Day 2"),
  q("notes-04", "notes", "Logistics", "Logistics optimisation variables include:",
    ["Only mesh size", "Routes and visit order", "Only colour", "Only eigenvalues"],
    1, "Multi-objective: time + fuel.", "Note p.7"),
  q("notes-05", "notes", "HVAC", "HVAC coupled chain order:",
    ["Energy → Occupancy → Heat → Cooling", "Occupancy → Heat → Cooling demand → Energy", "Only one model", "Random order"],
    1, "Coupling chain from note p.7.", "Note p.7"),
  q("notes-06", "notes", "AI surrogate", "AI surrogate for wing aerodynamics takes:",
    ["Only mesh as output", "Geometry inputs → lift/drag outputs (replaces expensive CFD)", "Only temperature", "Only RUL"],
    1, "Surrogate example note p.9.", "Note p.9"),
  q("notes-07", "notes", "Global min", "Global vs local minimum in optimisation:",
    ["Same thing", "Global = best in entire design space; local = best in neighbourhood", "Only for CAD", "Only for PCA"],
    1, "Optimisation trap question.", "Note p.3"),
  q("notes-08", "notes", "Categorical", "Categorical variable in DoE means:",
    ["Only continuous wind speed", "Discrete named levels (e.g. material A vs B)", "Only temperature", "Only mesh"],
    1, "Stochastic/categorical from lecture.", "Lecture 117"),
  q("notes-09", "notes", "Lifecycle trap", "Software dev 'Planning' phase is:",
    ["Same as product lifecycle 'Design & Analysis'", "Different framework — do not confuse with Prof's 5 lifecycle stages", "Same as Service", "Same as Manufacture"],
    1, "Common exam confusion.", "Quiz Q2 trap"),
  q("notes-10", "notes", "Exam", "Exam Q&A after presentation covers:",
    ["Only your antenna slides", "All course topics complementary to presentation (~70–90% theory)", "Only HEEDS", "Only Exercise 1"],
    1, "Prepare full theory — not just project.", "Exam Guidelines"),

  // ─── EXERCISES 1–2 & EXTRA TRAPS ───────────────────────────────
  q("official-25", "official", "Ex 1", "Exercise 1 Hooke's law: displacement uncertainty is:",
    ["±0.5 mm on displacement readings", "±0.5 N on force only", "Zero uncertainty", "±10 mm always"],
    0, "Measurement uncertainty affects confidence in spring constant k.", "Exercise 1"),
  q("official-26", "official", "Ex 1", "From F vs x plot, spring constant k is found by:",
    ["Slope of linear fit (convert mm to m for SI)", "Area under curve only", "Mesh size", "CAD volume"],
    0, "Least squares line fit → slope = k in N/m.", "Exercise 1"),
  q("official-27", "official", "Ex 2", "Exercise 2 AIAA paper: valuable company use case includes:",
    ["Only gaming", "Predictive maintenance reducing outages and inspection cost", "Only social media", "Only 2D drawings"],
    1, "Telecom/drone + prognostics aligns with your project.", "Exercise 2"),
  q("doe-13", "doe", "Fractional", "Fractional factorial DoE is used when:",
    ["Full factorial is too expensive for many factors", "Only one factor exists", "No simulation exists", "Only for PCA"],
    0, "Trade-off: fewer runs vs interaction information.", "Lecture 104"),
  q("heeds-11", "heeds", "Ex 7", "HEEDS Example 7 is:",
    ["Coil spring DoE", "Curve fitting / data matching", "Truss only", "FEM Ch31"],
    1, "Example 7 = curve fitting in guide.", "HEEDS Guide Ex 7"),
  q("heeds-12", "heeds", "Ex 8", "HEEDS Example 8 (Taguchi/RPD) relates to:",
    ["Only CAD import", "Robust parameter design — reduce sensitivity to noise", "Only meshing", "Only validation"],
    1, "Taguchi robust design = lecture robust design topic.", "HEEDS Ex 8"),
  q("fem-09", "fem", "Ex 9", "Correlation metrics for FEA vs test may include:",
    ["Only font size", "MAC, strain error %, R²", "Only CPU time", "Only Pugh scores"],
    1, "Exercise 9 validation metrics.", "Exercise 9"),
  q("functional-09", "functional", "Seals", "Rolls-Royce seal case illustrates:",
    ["Only marketing", "Multi-physics coupling at air/thermal/structural intersection", "Only 1D rod", "Only PCA"],
    1, "Prof's GT2020 seal coupling example.", "Quiz Q5 · Lecture"),
  q("vv-11", "vv", "Ex 1", "Fitting Hooke's law line to 15 data points then claiming model works at 10 N without new test is:",
    ["Validation", "Risky extrapolation / needs validation on new data", "Verification only", "Mesh convergence"],
    1, "Fit ≠ proof outside data range.", "Exercise 1 · Q12"),
  q("project-11", "project", "Pugh", "Full digital twin with RUL vs climber-only inspection — Pugh winner is typically:",
    ["Climber only — always cheapest", "Full twin — better accuracy, safety, predictive value", "No inspection ever", "Only 2D photos"],
    1, "Pugh matrix from Day 2 curriculum.", "Day 2 · Pugh"),
];

export function getQuestion(id: string): QuizQuestion | undefined {
  return QUIZ_BANK.find((x) => x.id === id);
}

export function getDeckQuestions(deckId: string): QuizQuestion[] {
  return QUIZ_BANK.filter((x) => x.deck === deckId);
}

export function getQuestionMap(): Record<string, QuizQuestion> {
  return Object.fromEntries(QUIZ_BANK.map((x) => [x.id, x]));
}
