export const QUIZ_DECKS = [
  {
    id: "official",
    title: "Official Quiz Q1–12",
    subtitle: "Prof. Nasti exercises PDF — verbatim traps",
    emoji: "📋",
    source: "DigitalTwin_Lectures_Exercises.pdf",
  },
  {
    id: "vv",
    title: "V&V Trap Questions",
    subtitle: "Verification · Validation · Calibration",
    emoji: "✅",
    source: "Quiz Q7–Q8 · Note p.2",
  },
  {
    id: "doe",
    title: "DoE · Pareto · Optimization",
    subtitle: "Monte Carlo · UQ · Robust design",
    emoji: "📊",
    source: "Lecture slides 102–119 · Note p.3",
  },
  {
    id: "heeds",
    title: "HEEDS & Process Automation",
    subtitle: "MDO workflow · Coil spring DoE",
    emoji: "⚙️",
    source: "HEEDS Guide · Exercise 5–6",
  },
  {
    id: "functional",
    title: "Functional Modelling & FMEA",
    subtitle: "P-diagram · Context · FFD · Pugh",
    emoji: "🔷",
    source: "Exercise 4 · Note p.5–8",
  },
  {
    id: "fem",
    title: "FEM & Simcenter",
    subtitle: "Chapter 31 · Exercises 7–9",
    emoji: "🔬",
    source: "FEM Ch.31 · Simcenter tutorials",
  },
  {
    id: "ml-pca",
    title: "ML · PCA · Surrogates",
    subtitle: "Exercises 10–12 · Note p.4",
    emoji: "🤖",
    source: "Lecture ML slides · Note p.4",
  },
  {
    id: "project",
    title: "Antenna RUL Project",
    subtitle: "Your presentation + numbers",
    emoji: "📡",
    source: "DigitalTwin_Antenna_RUL.ipynb",
  },
  {
    id: "notes",
    title: "Handwritten Notes Traps",
    subtitle: "Agile · TRL · Swiss cheese · HVAC",
    emoji: "📝",
    source: "Your 9 class note pages",
  },
] as const;
