#!/usr/bin/env python3
"""Generate day1.ts, day2.ts, day3.ts for TwinBlitz curriculum."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src/lib/curriculum"

AIAA = "https://www.aiaa.org/docs/default-source/uploadedfiles/issues-and-advocacy/policy-papers/digital-twin-institute-position-paper-(december-2020).pdf"
ASME_UNCERT = "https://www.asme.org/codes-standards/find-codes-standards/ptc-19-1-test-uncertainty"
NASA_TRL = "https://www.nasa.gov/directorates/heo/scan/engineering/technology/technology_readiness_level"
HEEDS_GUIDE = "file:///Users/msv/Downloads/HEEDSGettingStartedGuide.pdf"
BHW_FUNCTIONAL = "https://www.burgehugheswalsh.co.uk/downloads/Functional-Modelling-Handbook.pdf"
SIMCENTER = "https://docs.plm.automation.siemens.com/tdoc/nx/1872/simcenter_3d_tutorials.html#uid:index_advanced_sim_tutorial"
NOTEBOOK = "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb"
LECTURES_PDF = "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Lectures_Exercises.pdf"


def yt(id_, title):
    return {"id": id_, "title": title}


def res(title, url, type_="doc"):
    return {"title": title, "url": url, "type": type_}


def task(id_, day, block, slot, title, emoji, category, learn, practice, exercises, checklist, youtube, resources, xp):
    return {
        "id": id_, "day": day, "block": block, "slot": slot, "title": title, "emoji": emoji,
        "category": category, "learn": learn, "practice": practice, "exercises": exercises,
        "checklist": checklist, "youtube": youtube, "resources": resources, "xp": xp,
    }


def block(n, slot, label, tasks):
    return {"block": n, "slot": slot, "label": label, "tasks": tasks}


def emit_day(name, plan):
    lines = ['import type { DayPlan } from "./types";', "", f"export const {name}: DayPlan = "]
    lines.append(json.dumps(plan, indent=2, ensure_ascii=False))
    (OUT / f"{name}.ts").write_text("\n".join(lines) + ";\n", encoding="utf-8")
    print(f"Wrote {name}.ts — {sum(len(b['tasks']) for b in plan['blocks'])} tasks")


# ─── DAY 1 — Quiz Q1–12 + Exercises 1–2 ─────────────────────────────────────
day1 = {
    "day": 1, "date": "2026-06-08",
    "title": "Digital Twin Foundations — Quiz Q1–12",
    "subtitle": "Prof. Nasti Exercises PDF — every definition she will trap you on",
    "theme": "Master Quiz Q1–12 verbatim before Hooke's law lab and AIAA paper",
    "blocks": [
        block(1, "05:00–07:30", "📘 Quiz Q1–Q2 — Digital Twin & Lifecycle",
            [task("d1-b1-t1", 1, 1, "05:00–06:15", "Quiz Q1 — What Is the Digital Twin?", "🔄", "Theory",
                "Prof. Nasti's exact exam answer for Quiz Q1: 'The digital twin is the digital representation of a physical product throughout its lifecycle — the virtual product.' CRITICAL trap: students say 'a copy of the product' or 'a 3D model' — both are WRONG. The twin spans the ENTIRE lifecycle, not just design. The core is a fully coupled multi-disciplinary, multi-fidelity PARAMETRIC simulation model. Feeding real operational data into a system-level simulation creates a unique virtual model per real product. AIAA (Dec 2020) aligns: digital twin = virtual representation sufficient to meet lifecycle use cases. Prof fails anyone who says the digital twin REPLACES experimental testing — simulation cost << experimental cost, but BOTH are needed. Rolls-Royce Intelligent Engine is the canonical industrial example she cites.",
                "Write the definition on paper without looking — three attempts until word-perfect. Open the AIAA position paper executive summary and highlight every sentence containing 'lifecycle'. Record a 30-second oral answer. Compare your wording to Prof's: if you omitted 'throughout its lifecycle' or 'parametric', rewrite.",
                ["Recite digital twin definition verbatim (Prof's wording)", "State why '3D CAD model alone' is NOT a digital twin", "Name the core of every digital twin (coupled parametric simulation)", "Explain why DT does NOT replace experimental testing", "Give one Rolls-Royce / AIAA lifecycle use case"],
                ["Watched Rolls-Royce Intelligent Engine video", "Read AIAA paper introduction", "Definition written from memory 3×", "Oral 30-sec answer recorded", "Can explain to non-expert in 60 seconds"],
                [yt("9CcbYQ5QA70", "Rolls-Royce — Pioneering the Intelligent Engine"), yt("ObGhB9CCHP8", "Siemens — Digital Twin"), yt("9UpMeDO0A04", "Digital Twin Explained — Industry Overview")],
                [res("AIAA Digital Twin: Definition & Value (Dec 2020)", AIAA, "paper"), res("DigitalTwin Lectures & Exercises PDF", LECTURES_PDF, "doc")],
                50),
             task("d1-b1-t2", 1, 1, "06:15–07:30", "Quiz Q2 — Product Lifecycle Key Steps", "🔁", "Theory",
                "Quiz Q2 asks: 'What are the key steps of a product lifecycle?' Prof. Nasti lists FIVE stages in order: (1) Design & Analysis, (2) Manufacture, (3) Build & Assembly, (4) Experimental Testing, (5) Service. At EACH stage the digital twin lets you optimise and de-risk the real product by simulating behaviour for specific operating conditions. AIAA maps three twin stages onto this: AS-DESIGNED (before physical object — 3D CAD, material properties), AS-BUILT (after manufacturing — QC records, BOM), AS-USED/MAINTAINED (during operation — live sensor data). Exam trap: do NOT confuse lifecycle stages with software development stages (Planning→Maintenance) — those come on Day 2. Another trap: 'Release for Manufacture' is a design-process milestone, not a lifecycle stage in Prof's five.",
                "Draw the five-stage arrow diagram from memory. Under each stage write one digital-twin use case. Map AIAA as-designed / as-built / as-used onto Prof's five stages in a second column. Time yourself: list all five stages in ≤10 seconds.",
                ["List all 5 lifecycle stages in correct order", "One DT use case per stage", "Map AIAA 3 stages to Prof's 5 stages", "Distinguish lifecycle vs design process", "Why is 'Service' the as-used stage?"],
                ["Drew 5-stage diagram from memory", "Mapped AIAA stages", "Listed stages in ≤10 seconds", "Watched Siemens lifecycle video", "No confusion with software dev cycle"],
                [yt("ObGhB9CCHP8", "Siemens Digital Twin — Lifecycle"), yt("HftDI09LVI0", "ASME — Digital Twin Cities")],
                [res("AIAA Digital Twin Definition & Value", AIAA, "paper"), res("NASA TRL Scale", NASA_TRL, "doc")],
                48)]),
        block(2, "07:30–10:00", "📐 Quiz Q3–Q4 — Parametric Geometry & Accuracy",
            [task("d1-b2-t1", 1, 2, "07:30–08:45", "Quiz Q3 — Parametric Geometry Modelling", "📐", "Theory",
                "Quiz Q3: 'Why is parametric geometry modelling important to develop the concept of digital twin?' Answer: parametric CAD lets you simulate BOTH as-designed AND as-manufactured configurations from ONE master model — change a dimension parameter and the entire geometry, mesh, and boundary conditions update automatically. Without parametric geometry you cannot efficiently explore design space (DoE), run optimisation, or capture manufacturing variations (tolerances d = 35.0 ± 0.1 mm). The digital twin must stay synchronised with the real product across lifecycle stages; parametric models are the backbone. Geometry idealisation (simplified 3D, 2D slice, 1D beam) still derives from the parametric master — never a disconnected sketch. Prof trap: parametric ≠ just '3D CAD' — it means design variables drive geometry AND downstream simulation automatically.",
                "Open NX or any parametric CAD mental model: list 5 parameters for a telecom antenna mount (bracket thickness, bolt spacing, material). Explain how changing one parameter propagates to FEA mesh. Write 3 sentences answering Q3 for the oral exam.",
                ["Define parametric geometry in exam-ready prose", "Why needed for as-designed AND as-manufactured?", "Link parametric geometry to DoE/optimisation", "Give antenna project parameter example", "Parametric vs static CAD — difference?"],
                ["Answered Q3 in complete sentences", "Listed 5 antenna parameters", "Linked to design space exploration", "Understand geometry idealisation hierarchy", "No 'just 3D CAD' trap answer"],
                [yt("8u6dYTuBymA", "Ansys — Simulation-Driven Design"), yt("z_g-ov61DNw", "Building Ventilation CFD — Geometry Context")],
                [res("DigitalTwin Lectures PDF — Quiz Q3", LECTURES_PDF, "doc")],
                52),
             task("d1-b2-t2", 1, 2, "08:45–10:00", "Quiz Q4 — What Is Model Accuracy?", "⚖️", "Theory",
                "Quiz Q4: 'What is the accuracy of a model?' Prof. Nasti: ACCURACY = how close model predictions are to reality — covering geometry accuracy, behavioural accuracy, and dynamic accuracy. This is DISTINCT from FIDELITY (level of detail/realism in mirroring physical assets). Trade-off: RUN TIME vs ACCURACY — higher fidelity models take longer. The product lifecycle introduces variations the twin must capture: manufacturing variations, assembly tolerances, as-designed vs as-built differences, real operating conditions, aspects of physics NOT captured by simulation. Measurement uncertainty (e.g. d = 35.0 ± 0.1) reflects manufacturing tolerance — governed by ASME PTC 19.1 for test uncertainty. Exam trap: students define accuracy as 'how detailed the model is' — that is fidelity, not accuracy.",
                "Make a two-column table: Fidelity vs Accuracy with 3 examples each. Draw virtual product ↔ real product with four variation sources. Give concrete runtime-accuracy example: coarse FEA mesh = fast but less accurate stress prediction.",
                ["Define accuracy (Prof's three aspects)", "Define fidelity — two meanings from notes", "Runtime vs accuracy trade-off example", "What does d = 35.0 (±0.1) mean?", "Accuracy vs fidelity — exam trap?"],
                ["Table drawn from memory", "Virtual↔real diagram complete", "Oral answer ≤30 seconds", "Read ASME PTC 19.1 overview", "Never confuse fidelity with accuracy"],
                [yt("8u6dYTuBymA", "Ansys — Car Crash Simulation (fidelity)"), yt("cHThndE20oI", "Heat Transfer Simulation — Accuracy Context")],
                [res("ASME PTC 19.1 — Test Uncertainty", ASME_UNCERT, "paper")],
                50)]),
        block(3, "10:00–12:30", "🔗 Quiz Q5–Q6 — Coupling & Empirical Modelling",
            [task("d1-b3-t1", 1, 3, "10:00–11:15", "Quiz Q5 — Coupling in Physics-Based Models", "🔗", "Theory",
                "Quiz Q5: 'What does coupling mean in the context of physics-based models?' Prof. Nasti: MODEL COUPLING = 'Solving two or more models together in an iterative loop, because one's outputs are others' inputs — INTERDEPENDENT, cannot be solved independently.' Example — Smart Building HVAC: Occupancy↑ → Heat generation↑ → HVAC cooling demand↑ → Energy consumption↑. Models: Thermal, Occupancy, Airflow, Energy — coupled causal chain. Rolls-Royce seal case: seals sit at intersection of air system, thermal physics, flight loads — Prof's own ASME GT2020 paper. Exam trap: coupling ≠ simply 'connecting two software tools' (that is process automation). Coupling means physics interdependence requiring iterative solution.",
                "Draw the HVAC coupling chain with four models and directed arrows. Explain in three sentences why coupled models need iterative loops. For antenna tower digital twin: list four models that would couple (structural FEA + thermal + wind load + RUL prognostics).",
                ["Define coupling with word 'interdependent'", "Draw HVAC coupling chain", "Why can't coupled models be solved independently?", "Coupling vs process automation — difference?", "Antenna project coupling example"],
                ["HVAC diagram from memory", "Definition verbatim", "Distinguished coupling from automation", "Rolls-Royce seal context noted", "Oral answer practiced"],
                [yt("9CcbYQ5QA70", "Rolls-Royce — Multi-disciplinary Engine"), yt("z_g-ov61DNw", "Building HVAC Simulation Context")],
                [res("ASME GT2020 — Adele Nasti Seal Design Paper", "https://asmedigitalcollection.asme.org/GT/proceedings-abstract/GT2020/84188/V07CT14A023/1095072", "paper")],
                55),
             task("d1-b3-t2", 1, 3, "11:15–12:30", "Quiz Q6 — What Is an Empirical Model?", "📊", "Theory",
                "Quiz Q6: 'What is an empirical model?' Prof. Nasti: EMPIRICAL modelling starts from real-world observations and experimental data, using statistical methods to extract behaviour — curve fitting, regression, ML surrogates. Contrast PHYSICS-BASED: exploits laws of physics from first principles. Physics-based suits simple/fully-understood physics; empirical suits data-rich problems. In practice BOTH matter — even physics models need experimental validation. A model is a REPRESENTATION of reality; missed physics → calibration fixes this. Typical INPUTS: geometric parameters, operating conditions, operating envelope. Typical OUTPUTS: measurable attributes (temperature) or derived attributes (efficiency). Exam trap: empirical ≠ 'wrong' or 'less scientific' — it is the correct choice when physics is too complex or data is abundant.",
                "Classify each as physics-based or empirical: CFD, curve fitting, Arrhenius aging, neural network surrogate, Hooke's law spring. For 5G antenna project: list 3 inputs and 3 outputs. Define operating envelope.",
                ["Define empirical modelling (Prof's words)", "Define physics-based modelling", "3 inputs + 3 outputs for any model", "What is an operating envelope?", "When pick empirical over physics-based?"],
                ["Both definitions memorised", "Classification exercise done", "Antenna I/O listed", "Operating envelope explained", "Physics vs empirical — no value judgement"],
                [yt("64N2BY747Cw", "Rocket CFD — Physics-Based"), yt("_UVHneBUBW0", "StatQuest — Data-Driven Foundations")],
                [res("DigitalTwin Lectures PDF — Quiz Q6", LECTURES_PDF, "doc")],
                48)]),
        block(4, "12:30–15:00", "✅ Quiz Q7–Q8 — Validation, Calibration & V&V",
            [task("d1-b4-t1", 1, 4, "12:30–13:45", "Quiz Q7 — Validation vs Calibration", "🎯", "V&V",
                "Quiz Q7: 'What is the difference between model validation and model calibration?' VALIDATION: checks model predictions against real-world behaviour — 'Have I done the RIGHT maths?' Aims for ACCEPTABLE delta (subjective). Most common: compare to experimental test data OR higher-fidelity model. MODEL CALIBRATION (DATA MATCHING in your notes): adjusting internal model parameters to match experimental data — incorporates missed physics. Sequence trap Prof uses: you may calibrate THEN validate, but calibration is NOT validation. Calibration tunes parameters; validation assesses whether the tuned model agrees with independent reality. Example: calibrate wind exponent 1.6 in RUL model using field failures, then validate against held-out tower data.",
                "Write three exam Q&A cards: (1) calibrate then validate — order matters? (2) Is curve fitting calibration? (Yes — parameter estimation.) (3) Can you validate without calibrating? (Yes — physics-first models.) Practice complete-sentence oral answers.",
                ["Define model calibration / data matching", "Define model validation", "Calibration vs validation — key difference", "Can calibration replace validation?", "Antenna RUL calibration example"],
                ["Q7 answer word-perfect", "5 practice Q&A cards created", "Oral answers aloud", "ASME uncertainty context noted", "No mixing calibration with validation"],
                [yt("9x9LYvErnwk", "Model Validation in Simulation")],
                [res("ASME PTC 19.1 — Test Uncertainty", ASME_UNCERT, "paper"), res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc")],
                58),
             task("d1-b4-t2", 1, 4, "13:45–15:00", "Quiz Q8 — Verification vs Validation", "✅", "V&V",
                "Quiz Q8: 'What is the difference between verification and validation?' Prof. Nasti's favourite trap. VERIFICATION: 'Have I done the maths right?' — checks software implementation against expected results from the algorithm. Aims for ZERO error in code. Applies to simulation software development. VALIDATION: 'Have I done the right maths?' — checks model predictions against real-world behaviour. Examples: CFD vs wind tunnel = VALIDATION. FEA code vs analytical beam solution = VERIFICATION. Comparing two CFD codes = neither alone — context matters. V&V happens in software Testing phase of dev cycle. Prof fails vague answers — practice complete sentences.",
                "Create five V/V exam cards with answers. Record 60-second oral drill. Memory hook: Verification = code/maths correct; Validation = physics/model correct. Never say 'V&V' as one blob — Prof separates them.",
                ["Verification question verbatim", "Validation question verbatim", "CFD vs wind tunnel — V or V?", "FEA vs analytical beam — V or V?", "What does ±0.1 mean in d=35.0(±0.1)?"],
                ["V vs V memorised word-for-word", "5 exam cards with answers", "Oral drill recorded", "Read ASME PTC 19.1 overview", "Complete sentences only"],
                [yt("9x9LYvErnwk", "Model Validation in Simulation"), yt("pcLg6C_WlHg", "Structural Simulation — V&V Context")],
                [res("ASME PTC 19.1 — Test Uncertainty", ASME_UNCERT, "paper")],
                60)]),
        block(5, "15:00–17:30", "📈 Quiz Q9–Q10 — Geometry Idealisation & Curve Fitting",
            [task("d1-b5-t1", 1, 5, "15:00–16:15", "Quiz Q9 — Geometry Idealisation", "🏗️", "Theory",
                "Quiz Q9: 'What does geometry idealisation mean and why is it useful?' Geometry idealisation = simplifying complex CAD geometry before simulation while preserving physics of interest. Levels from notes: simplified 3D solid, 2D plane strain/stress slice, 1D beam/rod idealisation — ALL must stay synchronised with master parametric CAD. Useful because: (1) reduces mesh count and runtime, (2) removes irrelevant geometric detail (fillets, logos), (3) enables appropriate physics (2D symmetry, 1D thermal rod). Exam trap: idealisation ≠ 'bad model' — it is engineering judgement. Wrong idealisation (3D when 2D sufficient) wastes compute; wrong reduction (1D when stress concentrations matter) loses accuracy. Heated rod in FEM Ch31 is deliberate 1D idealisation.",
                "Sketch antenna tower: full 3D CAD → 2D frame slice → 1D beam for deflection check. For each level state what physics is kept vs dropped. Write Q9 answer in 4 sentences for oral exam.",
                ["Define geometry idealisation", "Name 3 idealisation levels", "Why useful — 3 reasons", "Must stay synced with master CAD?", "Heated rod — why 1D idealisation OK?"],
                ["3-level hierarchy drawn", "Q9 oral answer written", "Antenna idealisation example", "Linked to FEM Ch31 rod", "Idealisation ≠ inaccuracy trap avoided"],
                [yt("8u6dYTuBymA", "Simulation Geometry Preparation"), yt("cHThndE20oI", "1D Heat Transfer — Idealisation")],
                [res("DigitalTwin Lectures PDF — Quiz Q9", LECTURES_PDF, "doc")],
                50),
             task("d1-b5-t2", 1, 5, "16:15–17:30", "Quiz Q10 — What Is Curve Fitting?", "📈", "V&V",
                "Quiz Q10: 'What is curve fitting?' CURVE FITTING = generating a curve as close to experimental data as possible — empirical model creation from observations. Used for model calibration / data matching. Connects to Hooke's law Exercise 1: plot Force vs Displacement, fit line, extract spring constant k. Prof expects you to know fitting is NOT validation — you fit parameters, then validate predictions on new data. Interpolation (within data range) vs extrapolation (outside — Quiz Q12) follows from fitted curve. Surrogate models (Day 2–3) extend curve fitting to multi-dimensional response surfaces.",
                "Using Exercise 1 spring data (0.1 N → 7.3 mm through 1.5 N → 99.8 mm, uncertainty ±0.5 mm): plot by hand, identify linear region, state that curve fitting will yield k. Preview least squares for Q11.",
                ["Define curve fitting (Prof's words)", "Link curve fitting to calibration", "Exercise 1 — linear relationship expected?", "Fitting vs validation — difference?", "Connection to surrogate models"],
                ["Q10 definition memorised", "Spring data plotted on paper", "Linear F vs x relationship identified", "Linked to Exercise 1", "Calibration chain understood"],
                [yt("_UVHneBUBW0", "StatQuest — Fitting a Line to Data")],
                [res("DigitalTwin Lectures PDF — Exercise 1 Data", LECTURES_PDF, "doc"), res("IIT Data Analysis Using Graphs", "https://www.iit.edu/sites/default/files/2019-12/data_analysis.pdf", "doc")],
                48)]),
        block(6, "17:30–20:00", "📐 Quiz Q11–Q12 — Least Squares & Extrapolation",
            [task("d1-b6-t1", 1, 6, "17:30–18:45", "Quiz Q11 — Least Squares Method", "📐", "V&V",
                "Quiz Q11: 'What is the least square method and how does it work?' LEAST SQUARES estimates model parameters by MINIMISING Σ(yᵢ − f(xᵢ))² — sum of squared residuals between measured data and model predictions. Each term (yᵢ − f(xᵢ)) is a residual; squaring penalises large errors and makes calculus tractable. Used for curve fitting and model calibration. For Hooke's law: f(x) = kx, minimise Σ(Fᵢ − kxᵢ)² to find spring constant k in SI units (N/m after converting mm→m). Prof trap: least squares ≠ 'make line pass through all points' — overdetermined systems have no exact fit. Measurement uncertainty ±0.5 mm on displacement affects confidence in k.",
                "Write formula Σ(yᵢ−f(xᵢ))² and explain each symbol. Fit line by hand to three spring data points. Calculate k roughly from slope. State units conversion mm→m for SI.",
                ["Write least-squares residual formula", "Explain why residuals are squared", "Apply to Hooke's law f(x)=kx", "Overdetermined system — meaning?", "Effect of ±0.5 mm uncertainty?"],
                ["Formula from memory", "Hand calculation for k", "Units conversion explicit", "Connected to Exercise 1", "Oral explanation ≤45 sec"],
                [yt("_UVHneBUBW0", "StatQuest — Linear Regression & Least Squares")],
                [res("DigitalTwin Lectures PDF — Exercise 1", LECTURES_PDF, "doc"), res("Hooke's Law Reference", "https://phys.org/news/2015-02-law.html", "doc")],
                55),
             task("d1-b6-t2", 1, 6, "18:45–20:00", "Quiz Q12 — What Does Extrapolation Mean?", "⚠️", "V&V",
                "Quiz Q12: 'What does extrapolation mean?' EXTRAPOLATION = predicting OUTSIDE the range of measured/calibrated data — higher uncertainty than INTERPOLATION (within range). Dangerous for empirical models: fitted curve may diverge from true physics beyond data. Example: spring data only to 1.5 N — predicting at 5 N is extrapolation; linear Hooke assumption may fail (plastic deformation). For antenna RUL: DoE spans wind 5–35 m/s and temp 20–65°C — predicting at 40 m/s is extrapolation. Prof expects you to recommend staying inside operating envelope (wind≤12, temp≤30) rather than extrapolating.",
                "On same spring plot, mark interpolation zone (0.1–1.5 N) vs extrapolation zone (beyond 1.5 N). Write two sentences on risk. For antenna: identify when envelope plot stays inside vs outside DoE bounds.",
                ["Define extrapolation vs interpolation", "Why extrapolation is higher risk", "Spring example — beyond 1.5 N", "Antenna RUL extrapolation example", "Operating envelope avoids extrapolation?"],
                ["Both definitions memorised", "Zones marked on spring plot", "Antenna bounds identified", "Risk stated in complete sentences", "Linked to Day 3 envelope plot"],
                [yt("9x9LYvErnwk", "Simulation — Stay Within Valid Range")],
                [res("DigitalTwin Lectures PDF — Quiz Q12", LECTURES_PDF, "doc"), res("Your Antenna RUL Notebook", NOTEBOOK, "tool")],
                52)]),
        block(7, "20:00–23:00", "🧪 Exercises 1–2 — Hooke's Law Lab & AIAA Paper",
            [task("d1-b7-t1", 1, 7, "20:00–21:30", "Exercise 1 — Hooke's Law Spring Data Analysis", "🧪", "V&V",
                "Exercise 1 from Prof. Nasti's PDF: Physics-based vs empirical modelling — demonstrate physics via experiment, understand trends, fit curve to data. Design experiment validating Hooke's law. Data: Force (N) vs Displacement (mm) with ±0.5 mm uncertainty — 15 points from 0.1 N/7.3 mm to 1.5 N/99.8 mm. Tasks: (1) Plot data — relationship between dependent (displacement) and independent (force) variables. (2) Fit appropriate curve — predict spring constant k in SI units (N/m). Expect near-linear F–x; least squares on f(x)=kx. Convert mm to m before k calculation. This exercise IS Quiz Q10–Q11 in practice — Prof may ask k value in oral exam.",
                "Plot all 15 data points with error bars ±0.5 mm (Excel/Python/paper). Fit line via least squares. Compute k in N/m. Sanity check: R² or visual linearity. Write 2 sentences on physics-based (Hooke) vs empirical (fitted line) interpretation.",
                ["Plot Force vs Displacement with uncertainty bars", "Identify relationship (linear expected)", "Fit curve and compute k in SI (N/m)", "Show least squares working", "Physics-based vs empirical — 2 sentences"],
                ["All 15 points plotted", "k calculated in N/m", "Least squares shown", "Error bars included", "Ready to defend k in oral exam"],
                [yt("_UVHneBUBW0", "StatQuest — Fitting Hooke's Law Data")],
                [res("DigitalTwin Lectures PDF — Exercise 1", LECTURES_PDF, "doc"), res("Hooke's Law — phys.org", "https://phys.org/news/2015-02-law.html", "doc"), res("IIT Data Analysis Using Graphs", "https://www.iit.edu/sites/default/files/2019-12/data_analysis.pdf", "doc")],
                65),
             task("d1-b7-t2", 1, 7, "21:30–23:00", "Exercise 2 — AIAA Digital Twin White Paper", "📄", "Theory",
                "Exercise 2: Read AIAA white paper 'Digital Twin: Definition and Value' (Dec 2020). Answer: (1) What is in YOUR view a digital twin? (2) What use of digital twin could have value for a company? (3) Examples of products that could have a digital twin? Prof says language is technical — understand main ideas, not every sentence. Your exam answer for (1) must align with Quiz Q1 definition. For (2): predictive maintenance of telecom infrastructure using drone geometry + physics RUL — saves climber visits, reduces outages (~€220K industrial context). For (3): aero engines, smart buildings, racing motorcycles, centrifuges, injection molding, 5G antenna towers.",
                "Read AIAA executive summary and Section on Definition. Write full answers to all three questions in complete paragraphs. Map AIAA as-designed/as-built/as-used to your antenna project. Prepare for Lecture 2 open discussion format — Prof asks follow-ups.",
                ["Answer Q1 — your view of digital twin (align with Prof)", "Answer Q2 — valuable company use case", "Answer Q3 — five product examples", "Reference AIAA lifecycle stages", "Connect to antenna RUL project"],
                ["AIAA paper skimmed/read", "Three written answers complete", "Antenna project mapped to AIAA", "TRL 4–5 justified for project", "Discussion-ready paragraphs"],
                [yt("9UpMeDO0A04", "Digital Twin Use Cases Overview"), yt("ObGhB9CCHP8", "Siemens — Digital Twin Value")],
                [res("AIAA Digital Twin: Definition & Value (Dec 2020)", AIAA, "paper"), res("NASA TRL Scale", NASA_TRL, "doc"), res("DigitalTwin Lectures PDF — Exercise 2", LECTURES_PDF, "doc")],
                62)]),
    ]
}

# ─── DAY 2 — DoE, Optimisation, HEEDS, Exercises 4–6 ────────────────────────
day2 = {
    "day": 2, "date": "2026-06-09",
    "title": "DoE, Optimisation & HEEDS Mastery",
    "subtitle": "Exercises 4–6 + lecture topics Prof. Nasti drills on Pareto and HEEDS",
    "theme": "Design space exploration, UQ, process automation, then hands-on HEEDS/MATLAB",
    "blocks": [
        block(1, "05:00–07:30", "🧪 DoE — Four Types & Sensitivity",
            [task("d2-b1-t1", 2, 1, "05:00–06:15", "DoE Definition & Four Types", "🧪", "DoE",
                "DESIGN OF EXPERIMENTS (DoE): tool to explore design space and understand sensitivity of inputs on outputs — run multiple configurations, gather data. Four types from Prof's notes: (1) FULL FACTORIAL — all combinations of all parameter levels; estimates all main effects AND interactions; computationally expensive. (2) FRACTIONAL FACTORIAL — subset of full factorial; less info, more efficient. (3) SCREENING EXPERIMENTS — many parameters, few runs, identifies key variables. (4) LATIN HYPERCUBE — optimised space-filling sampling; captures non-linear effects with fewer runs. Design matrix: columns = inputs (in1, in2), column = output. Injection molding example: inputs = temperature, injection pressure, cooling time; outputs = part weight, dimensional deviation, surface quality, cycle time. Your antenna: 4 wind × 10 temp = 40 runs = full factorial.",
                "Build 2³ design matrix on paper for injection molding (3 inputs, 2 levels). Justify DoE type for: (a) 2 factors, 16-run budget → full factorial; (b) 20 factors, 30 runs → screening. Recreate antenna 40-run header.",
                ["Define DoE in Prof's words", "List 4 DoE types with trade-offs", "What is a design matrix?", "Injection molding — 3 inputs, 4 outputs", "Why full factorial for antenna (4×10)?"],
                ["4 types memorised", "Design matrix on paper", "Injection molding example ready", "Antenna 40-run justified", "Watched DoE intro videos"],
                [yt("_Rgue-7KDww", "JMP — Design of Experiments Process"), yt("PD_0QjEyQJk", "Minitab — DoE Introduction")],
                [res("DigitalTwin Lectures PDF — DoE", LECTURES_PDF, "doc"), res("Your Antenna RUL Notebook", NOTEBOOK, "tool")],
                52),
             task("d2-b1-t2", 2, 1, "06:15–07:30", "Sensitivity Analysis & Pareto Charts", "📊", "DoE",
                "SENSITIVITY ANALYSIS: studies how input parameter changes affect model output. Antenna method: sweep one factor across full range, hold other at midpoint — larger Δoutput = more sensitive factor. PARETO CHART ranks factors by impact on output. Antenna result: wind sweep (5→35 m/s at temp=42.5°C) gives larger RUL reduction than temp sweep (20→65°C at wind=20 m/s) — wind DOMINANT (~3.5× impact). Also know: main effects plots, interaction plots, parallel axes plots from lecture slide 106. Prof: 'Understanding sensitivity is crucial to design robust products.'",
                "Recalculate ΔRUL_wind and ΔRUL_temp from notebook. Draw Pareto bar chart on paper. Explain in two sentences why wind dominance is counterintuitive for electronics-focused engineers.",
                ["Define sensitivity analysis", "What does Pareto chart show?", "Dominant factor in antenna project?", "Main effects plot — purpose?", "Recalculate Δwind and Δtemp"],
                ["Deltas recalculated", "Pareto chart drawn", "Wind = dominant (~3.5×)", "Counterintuitive argument ready", "Notebook cells 12–14 reviewed"],
                [yt("9x9LYvErnwk", "DoE with FEA — Post-Processing"), yt("V_yaMyLeJ1I", "Isight Plugin within Abaqus CAE")],
                [res("Your Antenna RUL Notebook", NOTEBOOK, "tool")],
                55)]),
        block(2, "07:30–10:00", "🎯 Design Optimisation & Pareto Front",
            [task("d2-b2-t1", 2, 2, "07:30–08:45", "Design Optimisation — Objectives, Constraints, Variables", "🎯", "Optimization",
                "DESIGN OPTIMISATION: computational technique to find best design given objectives and constraints through iterative search. Prof's phrase: 'Swapping inputs & outputs — give target and ask model for inputs.' Component or system level. MULTI-OBJECTIVE: often conflicting objectives. Examples: (1) Seal — lowest leakage, mass ≤ x kg (Rolls-Royce). (2) Mug — max insulation, cost constraint. (3) Engine — min specific fuel consumption within safety margins. (4) Leaf seal — lowest leakage AND min heat at interface. Logistics: minimise delivery time + fuel cost; variables = routes/order; constraints = visit each customer once, fuel capacity, working hours. Antenna: OBJECTIVE = maximise RUL; VARIABLES = wind exposure, temperature; CONSTRAINTS = structural safety, data rate.",
                "Write optimisation problem statement for antenna project: objective, variables, constraints. Compare structure to logistics example from notes. Explain 'swap inputs and outputs' with one sentence example.",
                ["Define design optimisation", "DoE vs optimisation — difference?", "Antenna optimisation problem written", "Logistics example — obj/var/constraints", "What is multi-objective optimisation?"],
                ["Optimisation defined clearly", "Antenna problem written", "Logistics example known", "Objectives vs constraints distinguished", "HEEDS optim workflow previewed"],
                [yt("HvF_3Rok8RY", "HEEDS — Optimization Workflow")],
                [res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc")],
                50),
             task("d2-b2-t2", 2, 2, "08:45–10:00", "Pareto Front & Global vs Local Minimum", "📉", "Optimization",
                "PARETO FRONT: collection of optimal solutions between CONFLICTING objectives — feasible vs unfeasible designs; boundary = Pareto front. Example: stress vs mass — cannot minimise both; Pareto front shows trade-off curve. GLOBAL MINIMUM vs LOCAL MINIMUM: optimisation challenge is finding GLOBAL minimum (absolute best). Local minimum may suffice in some engineering problems. Method of steepest descent (gradient method). CATEGORICAL VARIABLE: discrete values. Exam trap: Pareto CHART (factor ranking from DoE) ≠ Pareto FRONT (multi-objective trade-off) — Prof tests both.",
                "Sketch stress-vs-mass Pareto front with feasible cloud. Mark local and global minimum on 1D curve. Answer: antenna wind vs temp — Pareto trade-off? (No — degradation drivers; operating envelope IS constraint boundary.)",
                ["Define Pareto front — 'conflicting objectives'", "Global vs local minimum", "Sketch stress vs mass Pareto front", "Pareto chart vs Pareto front?", "Define categorical variable"],
                ["Pareto front sketched", "Global vs local explained", "Chart vs front distinguished", "Antenna nuance understood", "Oral answer practiced"],
                [yt("HvF_3Rok8RY", "HEEDS — Multi-Objective Optimization"), yt("9x9LYvErnwk", "Optimization + DoE in Simulation")],
                [res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc")],
                55)]),
        block(3, "10:00–12:30", "🎲 Monte Carlo & Uncertainty Quantification",
            [task("d2-b3-t1", 2, 3, "10:00–11:15", "Monte Carlo Simulation", "🎲", "DoE",
                "MONTE CARLO: computational technique using RANDOM SAMPLING for complex deterministic problems (e.g. multi-objective optimisation with uncertainty). Each input gets PROBABILITY DISTRIBUTION (Gaussian or rectangular) → stochastic set of inputs → many deterministic runs. Useful for highly coupled physics or many input uncertainties. Swiss cheese model (lecture): layered defences — failures must align through every hole to cause incident; Monte Carlo samples many failure combinations. Example: wind speed Weibull at tower site → sample 1000 values → run RUL model 1000 times → RUL distribution.",
                "Explain Monte Carlo in three sentences. Describe stochastic set of inputs. Connect Swiss cheese: each layer = defence; Monte Carlo samples whether holes align.",
                ["Define Monte Carlo method", "What is stochastic set of inputs?", "Gaussian vs rectangular distribution?", "Swiss cheese model — 2 sentences", "Antenna wind variability example"],
                ["Monte Carlo defined", "Stochastic inputs explained", "Swiss cheese understood", "1000-run example sketched", "Connected to robust design"],
                [yt("PD_0QjEyQJk", "Statistical Methods — Monte Carlo Context")],
                [res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc")],
                50),
             task("d2-b3-t2", 2, 3, "11:15–12:30", "Uncertainty Quantification (UQ)", "📏", "DoE",
                "UNCERTAINTY QUANTIFICATION: identify uncertainty sources, estimate input uncertainties, propagate to output uncertainties. Types: STATISTICAL (random noise) vs SYSTEMATIC (bias/offset from test setup). Propagation: x₁±δx₁ → effect on R; combined via ROOT SUM SQUARE (RSS). UNCERTAINTY QUANTIFICATION from notes: nominal value + distribution variation. Robust design = low sensitivity of outputs to input variation. ASME PTC 19.1 governs test uncertainty — links to Quiz Q4 measurement ±0.1 and Exercise 1 ±0.5 mm displacement.",
                "List three uncertainty sources for antenna RUL model (wind measurement, temperature sensor, material aging coefficients). Show RSS combination concept. Distinguish statistical vs systematic with one example each.",
                ["Define UQ from notes", "Statistical vs systematic uncertainty", "Root sum square combination", "What makes design 'robust'?", "Link to ASME PTC 19.1"],
                ["UQ types memorised", "3 antenna uncertainty sources", "RSS concept explained", "ASME link noted", "Robust design defined"],
                [yt("9x9LYvErnwk", "Simulation Uncertainty Context")],
                [res("ASME PTC 19.1 — Test Uncertainty", ASME_UNCERT, "paper")],
                52)]),
        block(4, "12:30–15:00", "📋 Pugh, FMEA & Swiss Cheese",
            [task("d2-b4-t1", 2, 4, "12:30–13:45", "Pugh Matrix — Concept Selection", "📋", "Functional",
                "PUGH MATRIX: decision-making tool comparing multiple concepts against criteria by scoring (+/−/S same). Use early in conceptual design when choosing between alternatives. DATA MATCHING = MODEL CALIBRATION — tuning parameters to match experimental data (Prof notes p.3). For antenna: Pugh compare (A) periodic climber inspection, (B) drone photogrammetry only, (C) full digital twin with RUL. Criteria: cost, safety, accuracy, scalability, maintenance interval.",
                "Create 3-concept × 5-criteria Pugh matrix for antenna monitoring approaches. Score +/−/S. Identify winner. Write two sentences: data matching = calibration for RUL f_wind exponent and Arrhenius coefficient.",
                ["Define Pugh matrix purpose", "Data matching = what?", "Build 3×5 Pugh matrix", "Which concept wins?", "RUL parameters to calibrate?"],
                ["Pugh matrix completed", "Winner identified", "Data matching = calibration", "Calibration limits acknowledged", "Honest limitation for presentation"],
                [yt("SwgtZp4Jcjs", "Isight — Decision Support Context")],
                [res("BHW Functional Modelling Handbook", BHW_FUNCTIONAL, "doc"), res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc")],
                45),
             task("d2-b4-t2", 2, 4, "13:45–15:00", "FMEA & Swiss Cheese Model", "🧀", "Functional",
                "FMEA table structure from Prof's notes: Process, Failure Mode, Failure Effect, SEVERITY, Cause, OCCURRENCE, Current controls, DETECTION, RPN/TOTAL. Line-on-line interference → almost no wear (class example). SWISS CHEESE MODEL: multiple defensive layers (design review, simulation V&V, testing, maintenance); failure requires holes to align through ALL layers — connects to Monte Carlo sampling of failure combinations. For antenna: FMEA row — 'Structural failure due to wind fatigue' with S/O/D scores.",
                "Fill one complete FMEA row for antenna structural wind fatigue failure. Draw Swiss cheese with 4 layers labelled for digital twin workflow (CAD, simulation, drone inspection, RUL monitoring).",
                ["FMEA column headers from memory", "One antenna FMEA row complete", "Swiss cheese — 2 sentence definition", "Line-on-line interference example", "Link FMEA to digital twin layers"],
                ["FMEA row filled", "Swiss cheese diagram drawn", "S/O/D scales understood", "Class example recalled", "Connected to Monte Carlo task"],
                [yt("HftDI09LVI0", "Systems Safety — Layered Defences")],
                [res("DigitalTwin Lectures PDF — FMEA", LECTURES_PDF, "doc")],
                48)]),
        block(5, "15:00–17:30", "⚙️ Process Automation, Integrated Design & Agile",
            [task("d2-b5-t1", 2, 5, "15:00–16:15", "Process Automation — Four Pillars", "⚙️", "HEEDS",
                "PROCESS AUTOMATION (Prof notes): brings the design process into software — links multiple simulation tools via automated data transfers = INTEGRATED DESIGN SYSTEMS (simulation framework). Four pillars from lecture: (1) CAD integration (NX), (2) simulation tools (Simcenter/Ansys), (3) DoE & optimisation (HEEDS/iSight), (4) data management & workflow orchestration. Benefits: speed up process, improve product attributes, repeatability. HEEDS + iSight = Siemens/Simulia automation stack. This is exactly what your Python notebook replicates manually for antenna RUL.",
                "List four pillars with tool example each. Explain process automation in one sentence. Map notebook cells to HEEDS workflow: Design Space → DoE → Response Surface → Optimisation/envelope.",
                ["Define process automation", "What are Integrated Design Systems?", "Name 4 pillars with tools", "HEEDS + iSight purpose", "Notebook ↔ HEEDS mapping"],
                ["4 pillars memorised", "HEEDS workflow mapped to notebook", "Process automation defined", "Watched HEEDS overview", "Read HEEDS getting started intro"],
                [yt("HvF_3Rok8RY", "HEEDS — Multi-Disciplinary Design Exploration"), yt("SwgtZp4Jcjs", "Isight — Process Automation Overview")],
                [res("HEEDS Getting Started Guide", HEEDS_GUIDE, "doc")],
                55),
             task("d2-b5-t2", 2, 5, "16:15–17:30", "Integrated Design & Agile Development", "🔄", "Tools",
                "INTEGRATED DESIGN: multidisciplinary, multi-fidelity, simulation-driven — risk level drives accuracy/fidelity needed. AGILE: iterative incremental project management — flexibility, customer collaboration, rapid value delivery; contrast to waterfall. SOFTWARE DEV CYCLE (notes p.5): (1) Planning, (2) Analysis, (3) Design, (4) Implementation, (5) Testing & integration, (6) Maintenance. VERIFICATION happens in Testing phase. Your Jupyter notebook: Planning (objective) → Analysis (RUL physics) → Design (DoE matrix) → Implementation (Python) → Testing (sanity checks 5/15/35 m/s) → Maintenance (extend with sensor data).",
                "List 6 software dev cycle stages. Map notebook to each. Define Agile in one sentence. Answer: 'How is simulation software development different from app development?' — verification against analytical solutions is critical.",
                ["List 6 software development stages", "Define Agile from notes", "Map notebook to 6 stages", "Where does verification fit?", "Agile vs waterfall — one difference"],
                ["6 stages memorised", "Notebook mapped", "Agile defined", "Verification in testing phase", "Simulation vs app dev answer ready"],
                [yt("SwgtZp4Jcjs", "Isight — Agile Workflow Integration")],
                [res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc"), res("Your Antenna RUL Notebook", NOTEBOOK, "tool")],
                48)]),
        block(6, "17:30–20:00", "🔧 TRL, Mesh Convergence & Toolchain",
            [task("d2-b6-t1", 2, 6, "17:30–18:45", "Technology Readiness Levels (TRL)", "🚀", "Tools",
                "NASA TRL 1–9 scale: TRL 1 basic principles, TRL 4 component validation in lab, TRL 5 validation in relevant environment, TRL 6 system prototype demonstration, TRL 7 operational prototype, TRL 9 deployed system. Your antenna project ≈ TRL 4–5: validated RUL model in simulation/lab, drone photogrammetry demonstrated industrially (~€220K contract) but full tower-scale predictive maintenance not deployed at scale. Prof asks TRL in Q&A — justify with evidence, not aspiration.",
                "Read NASA TRL page. Write 3 sentences placing antenna project at TRL 4–5 with evidence. List what would be needed to reach TRL 7 (field sensors, live twin feed, maintenance action closure).",
                ["Define TRL scale (1–9 overview)", "Where is antenna project?", "Evidence for TRL 4–5", "Gap to TRL 7?", "TRL vs technology maturity — oral answer"],
                ["NASA TRL page read", "TRL 4–5 justified in writing", "Gap analysis done", "Oral answer ≤30 sec", "No inflated TRL claim"],
                [yt("9UpMeDO0A04", "Digital Twin Maturity Context")],
                [res("NASA TRL Scale", NASA_TRL, "doc")],
                45),
             task("d2-b6-t2", 2, 6, "18:45–20:00", "Mesh Convergence & NX/Simcenter/HEEDS Tools", "🔧", "Tools",
                "MESH CONVERGENCE STUDY: (1) coarse mesh, (2) systematic refinement, (3) simulation iterations, (4) check convergence. Software toolchain from notes: CAD=NX, Dynamic=NX/MSC Nastran, General FEA=Ansys/Abaqus, Contact=LS-Dyna, Mesh-free=Simsolid, Automation=HyperWorks/HyperMesh, Optimisation=HEEDS+iSight, Simcenter 3D for integrated FEA/thermal/response dynamics (Exercises 7–9). Antenna uses analytical model — explain WHEN you'd need Simcenter FEA instead (stress concentrations, nonlinear material, validation correlation).",
                "Write 4 mesh convergence steps from memory. List 8 tools with purpose. Prepare one sentence: 'Analytical RUL sufficient for system-level DoE; FEA needed for local stress validation.'",
                ["4 mesh convergence steps", "8 software tools from notes", "When analytical vs FEA?", "What is Simsolid?", "Simcenter role in Exercises 7–9"],
                ["Convergence steps memorised", "Toolchain listed", "Analytical vs FEA answer ready", "Simcenter tutorial bookmarked", "Rolls-Royce seal context noted"],
                [yt("8u6dYTuBymA", "FEA Simulation Example"), yt("V_yaMyLeJ1I", "Simcenter/Abaqus Integration")],
                [res("Simcenter 3D Tutorials", SIMCENTER, "doc"), res("HEEDS Getting Started Guide", HEEDS_GUIDE, "doc")],
                50)]),
        block(7, "20:00–23:00", "📊 Exercises 4–6 — P-diagram, HEEDS, MATLAB",
            [task("d2-b7-t1", 2, 7, "20:00–21:30", "Exercise 4 — P-Diagram, Context & FFD Antenna Tower", "📡", "Functional",
                "Exercise 4: Create P-diagram, context diagram, and functional flow diagram for a product — complex or simple; may become final assignment. YOUR PRODUCT: 5G/6G telecom antenna tower digital twin. P-DIAGRAM centre: 'Maintain antenna structural integrity & predict RUL.' INPUTS: wind speed, ambient temperature, drone-derived geometry, load history. NOISE: weather variability, material batch variation, unmeasured vibration. CONTROLS: inspection interval, operating envelope limits, maintenance threshold. IDEAL RESPONSE: accurate RUL, minimal outages. ERROR STATE: RUL underestimate → late maintenance; overestimate → unsafe operation. FFD: Monitor (sensors/drone) → Compare (RUL vs threshold) → Adjust (maintenance schedule) → Predict (degradation trend) → Feedback. Context diagram: tower, drone, cloud analytics, maintenance crew.",
                "Draw P-diagram, context diagram, and FFD for antenna tower from memory. Use BHW Functional Modelling Handbook structure. Prof trap: FFD ≠ software architecture — abstraction of real problem. Connect to motorcycle traction FFD from Day 1 notes.",
                ["P-diagram — all 5 zones for antenna", "Context diagram — 4+ entities", "FFD — 4-step flow with feedback", "FFD ≠ software architecture", "Noise vs control factors — 3 each"],
                ["All three diagrams drawn", "BHW handbook consulted", "Motorcycle FFD compared", "Oral explanation practiced", "Ready for Exercise 4 submission"],
                [yt("ObGhB9CCHP8", "Siemens — Smart Infrastructure Context")],
                [res("BHW Functional Modelling Handbook", BHW_FUNCTIONAL, "doc"), res("DigitalTwin Lectures PDF — Exercise 4", LECTURES_PDF, "doc"), res("ASME GT2020 Nasti Seal Paper", "https://asmedigitalcollection.asme.org/GT/proceedings-abstract/GT2020/84188/V07CT14A023/1095072", "paper")],
                58),
             task("d2-b7-t2", 2, 7, "21:30–23:00", "Exercise 5 HEEDS Coil Spring & Exercise 6 MATLAB optimproblem", "⚙️", "HEEDS",
                "Exercise 5: HEEDS Training — install per campusnet guidelines. Examples: Example 5 DoE Study of Coil Spring; Example 10 Multi-objective optimisation. Read HEEDS Getting Started Guide. Exercise 6: MATLAB Optimisation Toolbox — optimproblem, optimvar, optimconstr, optimexpr; tutorial on MathWorks; optional optimal path video. Map HEEDS coil spring DoE to your antenna factorial: both define design space, run experiments, analyse responses. Multi-objective in HEEDS Example 10 parallels Pareto front lecture — conflicting objectives, trade-off curve.",
                "Open HEEDS guide — identify Design Space, Response Surface, Optimisation workflow steps. If HEEDS unavailable: document equivalent notebook workflow. In MATLAB (or read docs): write pseudocode for optimproblem with one objective and one constraint. Compare coil spring DoE to antenna 40-run matrix.",
                ["HEEDS Example 5 — coil spring DoE steps", "HEEDS Example 10 — multi-objective goal", "MATLAB optimproblem pseudocode", "optimvar / optimconstr roles", "Map HEEDS workflow to notebook"],
                ["HEEDS guide sections identified", "Coil spring ↔ antenna DoE compared", "MATLAB functions listed", "Multi-objective linked to Pareto", "Process automation demonstrated"],
                [yt("HvF_3Rok8RY", "HEEDS — DoE & Optimization"), yt("SwgtZp4Jcjs", "Isight — MATLAB Integration"), yt("_Rgue-7KDww", "DoE Process — Coil Spring Analog")],
                [res("HEEDS Getting Started Guide", HEEDS_GUIDE, "doc"), res("DigitalTwin Lectures PDF — Exercises 5–6", LECTURES_PDF, "doc"), res("Your Antenna RUL Notebook", NOTEBOOK, "tool")],
                62)]),
    ]
}

# ─── DAY 3 — FEM Ch31, Exercises 7–12, Project, PCA, Surrogate ───────────────
day3 = {
    "day": 3, "date": "2026-06-10",
    "title": "FEM, Simcenter Labs, Project & Exam Presentation",
    "subtitle": "Chapter 31 FEM + Exercises 7–12 + Antenna RUL project + PCA/surrogate",
    "theme": "Close every gap — FEA theory, hands-on exercises, project fluency, presentation",
    "blocks": [
        block(1, "05:00–07:30", "🔬 FEM Ch31 — Discretization & Element Equations",
            [task("d3-b1-t1", 3, 1, "05:00–06:15", "FEM Discretization, Elements & Nodes", "🔬", "FEA",
                "FEM Ch31 (Prof. Nasti / Kreyszig): Unlike finite-difference pointwise grids, FEM divides domain into simply shaped ELEMENTS (1D line, 2D triangle/quad, 3D brick). Nodes = intersection points of element boundaries; sides = nodal lines/planes. DISCRETIZATION step divides solution domain — better for irregular geometry, unusual BCs, heterogeneous composition (gasket Fig 31.1). Values of unknown can be generated continuously across domain rather than isolated points. General FEM steps: (1) Discretization, (2) Element equations, (3) Assembly, (4) BCs, (5) Solution, (6) Postprocessing.",
                "Sketch 1D line element with nodes x1, x2. Sketch 2D triangular element (Fig 31.9). List all 6 FEM steps from Sec 31.1. Explain why FEM beats finite-difference for irregular gasket geometry.",
                ["List 6 FEM steps (31.1)", "Define discretization", "Node vs element — difference?", "1D vs 2D element examples", "Why FEM for irregular geometry?"],
                ["6 steps memorised", "1D and 2D elements sketched", "Gasket example explained", "Ch31 slides reviewed", "Linked to Simcenter Exercises 7–9"],
                [yt("pcLg6C_WlHg", "Structural FEM Simulation Overview"), yt("8u6dYTuBymA", "FEA Discretization Context")],
                [res("DigitalTwin Lectures PDF — FEM Ch31", LECTURES_PDF, "doc")],
                52),
             task("d3-b1-t2", 3, 1, "06:15–07:30", "Shape Functions & [k]{u}={F}", "📐", "FEA",
                "ELEMENT EQUATIONS: choose approximation function — polynomials common. 1D linear: u(x) = a₀ + a₁x (Eq 31.1), must pass nodal values at x1, x2. Shape/interpolation functions (Fig 31.3) express u at any point via nodal values. Methods: direct approach, weighted residuals, variational — outcome like curve fitting to PDE. Element equations → linear system [k]{u} = {F} (Eq 31.9): [k] = element stiffness/property matrix, {u} = nodal unknowns, {F} = external nodal loads. Some systems nonlinear; Ch31 examples linear. Optimal fit minimises PDE residual in weighted sense.",
                "For 1D linear element write u(x)=a₀+a₁x and explain nodal boundary conditions. Define [k], {u}, {F} in one sentence each. Connect shape functions to Quiz Q10 curve fitting — same maths, different target (PDE not data).",
                ["Write 1D linear approximation u(x)", "Define shape/interpolation functions", "Write [k]{u}={F} — define each term", "Three element equation methods", "Link to curve fitting concept"],
                ["Equation 31.1 written", "[k]{u}={F} defined", "Shape functions understood", "PDE vs data fitting noted", "Ready for heated rod example"],
                [yt("pcLg6C_WlHg", "FEA Shape Functions Context")],
                [res("DigitalTwin Lectures PDF — Ch31 Element Equations", LECTURES_PDF, "doc")],
                55)]),
        block(2, "07:30–10:00", "🔥 FEM Ch31 — Assembly, Heated Rod, 2D, Postprocessing",
            [task("d3-b2-t1", 3, 2, "07:30–08:45", "Assembly & 1D Heated Rod", "🔥", "FEA",
                "ASSEMBLY (Sec 31.2.3): global numbering scheme defines topology/connectivity (Table 31.1). Element equations written in global coordinates, added sequentially → total system matrix (Fig 31.7). HEATED ROD (Fig 31.4): 1D steady-state, fixed end temperatures, uniform heat source — four equal elements, five nodes. Even without PDEs in full detail, rod demonstrates all FEM steps unencumbered. Solution via LU decomposition; banded matrices for efficiency. Result (Fig 31.8): FEM captures trend, exact match AT NODES; interior discrepancy due to linear shape functions.",
                "Draw heated rod with 4 elements, 5 nodes. Write assembly concept in 3 sentences. Explain why FEM matches exact solution at nodes but not necessarily between nodes.",
                ["Assembly step — 3 sentences", "Global numbering — why important?", "Heated rod setup (BCs, source)", "Exact at nodes — why?", "Linear shape function limitation"],
                ["Rod diagram drawn", "Assembly explained", "Fig 31.8 behaviour understood", "Banded matrix note taken", "1D application complete"],
                [yt("cHThndE20oI", "Heat Transfer FEM — Heated Rod")],
                [res("DigitalTwin Lectures PDF — Ch31 Heated Rod", LECTURES_PDF, "doc")],
                50),
             task("d3-b2-t2", 3, 2, "08:45–10:00", "2D Triangular Elements & Postprocessing", "📊", "FEA",
                "2D PROBLEMS (Sec 31.3): extend FEM conceptually — same steps, more bookkeeping. Triangular elements common (Fig 31.9). Linear approximate function over triangle (Fig 31.10) with interpolation functions (b)–(d). Numbering scheme critical for bandedness (Fig 31.11 heated plate). BCs and assembly more complex in 2D/3D but conceptually same. POSTPROCESSING: display tabular/graphical results; compute secondary variables (stress, flux). Fig 31.12 2D solution corresponds to prior finite-difference plate solution. Simcenter Exercises 7–9 apply 2D/3D thermal and structural postprocessing.",
                "Sketch triangular element with three nodes. List postprocessing outputs for thermal PCB (Exercise 7): temperature field, heat flux, hotspot under chip. Connect heated plate numbering (Fig 31.11) to mesh convergence study from Day 2.",
                ["2D triangular element sketched", "Postprocessing — 3 output types", "Numbering affects bandedness?", "Secondary variables — examples", "Link to Simcenter thermal PCB"],
                ["Triangle element drawn", "Postprocessing list complete", "2D vs 1D bookkeeping noted", "Simcenter tutorial opened", "Mesh convergence linked"],
                [yt("z_g-ov61DNw", "2D Thermal Simulation — Postprocessing"), yt("cHThndE20oI", "Temperature Field Visualization")],
                [res("Simcenter 3D Tutorials", SIMCENTER, "doc")],
                52)]),
        block(3, "10:00–12:30", "🌡️ Exercises 7–8 — Simcenter Thermal & Response Dynamics",
            [task("d3-b3-t1", 3, 3, "10:00–11:15", "Exercise 7 — Simcenter Thermal PCB Analysis", "🌡️", "FEA",
                "Exercise 7: Finite Element Analysis with Simcenter 3D. Tutorial base at Simcenter 3D tutorials index. Specific exercise: Thermal modelling — Analysing a Printed Circuit Board with a chip (xid1688538). Additional Nastran getting started PDF. Workflow: import CAD → mesh PCB + chip → thermal BCs (power dissipation hotspot) → solve → postprocess temperature field. Links Quiz Q9 geometry idealisation (chip detail vs board simplification) and Quiz Q8 V&V (correlate hotspot prediction to thermocouple test).",
                "Open Simcenter thermal PCB tutorial. Document workflow steps: geometry, mesh, materials, BCs, solve, postprocess. Even if software unavailable, write step list from tutorial PDF. Identify one verification and one validation action for PCB model.",
                ["Simcenter tutorial URL bookmarked", "PCB thermal workflow — 6 steps", "Hotspot BC definition", "Postprocess: max temp location", "One V and one V action listed"],
                ["Tutorial steps documented", "Idealisation choices noted", "V&V actions identified", "Nastran PDF located", "Linked to Ch31 postprocessing"],
                [yt("cHThndE20oI", "Thermal FEA — PCB Context"), yt("z_g-ov61DNw", "Electronics Cooling Simulation")],
                [res("Simcenter 3D Tutorials", SIMCENTER, "doc"), res("Simcenter Nastran Getting Started", "https://docs.plm.automation.siemens.com/data_services/resources/scnastran/2020_1/help/tdoc/en_US/pdf/getting_started.pdf", "doc"), res("DigitalTwin Lectures PDF — Exercise 7", LECTURES_PDF, "doc")],
                55),
             task("d3-b3-t2", 3, 3, "11:15–12:30", "Exercise 8 — Response Dynamics FEM + Transient", "📳", "FEA",
                "Exercise 8: Response Dynamics with Simcenter 3D. Two parts: (1) Setting up the FEM (xid1677563), (2) Analyzing a transient event (xid1677679). Transient = time-dependent response (impact, vibration pulse) vs steady-state heated rod. FEM setup: mesh, material damping, constraints. Transient: time stepping, record displacement/acceleration history. Connects to Quiz Q5 coupling (structural ↔ thermal ↔ dynamic). Antenna tower: wind gust = transient load — steady RUL model vs transient FEA refinement.",
                "Document Exercise 8 two-part workflow. Contrast steady-state (heated rod) vs transient (response dynamics). For antenna: when would transient FEA matter vs analytical RUL?",
                ["Exercise 8 Part 1 — FEM setup steps", "Exercise 8 Part 2 — transient analysis", "Steady vs transient — difference", "Output: time history of ?", "Antenna — transient relevance?"],
                ["Both tutorial links saved", "Steady vs transient explained", "Time history outputs listed", "Antenna connection made", "Dynamic FEA vocabulary ready"],
                [yt("pcLg6C_WlHg", "Structural Dynamics FEM"), yt("64N2BY747Cw", "Transient Simulation Context")],
                [res("Simcenter 3D Tutorials — Response Dynamics", SIMCENTER, "doc"), res("DigitalTwin Lectures PDF — Exercise 8", LECTURES_PDF, "doc")],
                55)]),
        block(4, "12:30–15:00", "🔗 Exercises 9–10 — FEA/Test Correlation & ML Onramp",
            [task("d3-b4-t1", 3, 4, "12:30–13:45", "Exercise 9 — Correlate FEA with Test Results", "🔗", "V&V",
                "Exercise 9: Correlate structural analysis results with test solution (Simcenter tutorial xid1731225). This IS model VALIDATION (Quiz Q8): 'Have I done the right maths?' — compare FEA predictions to strain gauge / DIC / modal test data. Process: run FEA → run physical test → overlay results → quantify delta → calibrate if needed (Quiz Q7) → re-validate. ASME PTC 19.1 uncertainty on test data. Correlation metrics: MAC (modal), strain error %, Coefficient of Determination R².",
                "Write validation workflow for antenna bracket: FEA modal analysis vs shaker test. List three metrics to compare. If delta too large: which parameters to calibrate first (Young's modulus, damping, boundary conditions)?",
                ["Exercise 9 workflow — 5 steps", "Validation vs calibration order", "Three correlation metrics", "ASME uncertainty role", "Antenna bracket validation plan"],
                ["Workflow documented", "Metrics listed", "Calibration parameters identified", "V&V definitions applied", "Tutorial link saved"],
                [yt("9x9LYvErnwk", "FEA Model Validation"), yt("pcLg6C_WlHg", "Test-Correlation Workflow")],
                [res("Simcenter 3D Tutorials — Correlation", SIMCENTER, "doc"), res("ASME PTC 19.1 — Test Uncertainty", ASME_UNCERT, "paper"), res("DigitalTwin Lectures PDF — Exercise 9", LECTURES_PDF, "doc")],
                58),
             task("d3-b4-t2", 3, 4, "13:45–15:00", "Exercise 10 — MATLAB Machine Learning Onramp", "🤖", "ML",
                "Exercise 10: MATLAB Machine Learning Onramp (MathWorks tutorial). Introduces supervised learning workflow: import data → preprocess → select features → train model → evaluate. Connects to Quiz Q6 empirical models and Day 2 surrogate models. ML as surrogate on simulation datasets — wing aerodynamics example from notes: inputs = wing geometry, outputs = lift/drag; AI predicts CFD faster. For antenna: ML could surrogate RUL surface from 40-run DoE — but physics interpretability trade-off.",
                "Complete ML Onramp OR document its module list. Answer: 'Could ML replace your RUL formula?' — Yes with enough FEA/field data; lose physics interpretability; need validation on held-out data. List supervised vs unsupervised — PCA (Day 3 block 7) is unsupervised.",
                ["ML Onramp modules listed/completed", "Supervised learning workflow — 5 steps", "ML as surrogate — pros/cons", "Antenna: ML on 40-run data?", "Supervised vs unsupervised"],
                ["Onramp started or modules mapped", "Surrogate connection made", "Interpretability trade-off stated", "Validation requirement noted", "Linked to Exercise 11 prognosis"],
                [yt("_UVHneBUBW0", "StatQuest — ML Foundations"), yt("FgakZw6K1QQ", "StatQuest — PCA (unsupervised contrast)")],
                [res("MATLAB Machine Learning Onramp", "https://de.mathworks.com/learn/tutorials/machine-learning-onramp.html", "tool"), res("DigitalTwin Lectures PDF — Exercise 10", LECTURES_PDF, "doc")],
                50)]),
        block(5, "15:00–17:30", "⚡ Exercises 11–12 — Bearing Prognosis & DRL Pump",
            [task("d3-b5-t1", 3, 5, "15:00–16:15", "Exercise 11 — Wind Turbine Bearing Prognosis", "⚡", "ML",
                "Exercise 11: Diagnostics and Degradation Models with MATLAB — Wind Turbine High-Speed Bearing Prognosis example + exponentialdegradationmodel reference. Prognostics = predict RUL from degradation signals — DIRECT parallel to your antenna RUL project. Exponential degradation model: parametric fit to health index trend. Compare physics-based antenna RUL (Arrhenius × wind fatigue) vs data-driven bearing prognosis. Both answer: 'When will it fail?' Prof may ask you to compare approaches in Q&A.",
                "Read bearing prognosis example outline. Map its workflow to antenna: sensor data → health index → degradation model → RUL forecast. Write 3 sentences comparing physics-based vs data-driven prognostics for antenna towers.",
                ["Exercise 11 workflow — 4 steps", "exponentialdegradationmodel purpose", "Prognostics vs diagnostics", "Parallel to antenna RUL project", "Physics vs data-driven — 3 sentences"],
                ["Bearing example read", "Workflow mapped to antenna", "Comparison written", "Degradation model defined", "Q&A answer prepared"],
                [yt("9UpMeDO0A04", "Predictive Maintenance — Prognostics Context")],
                [res("MATLAB Wind Turbine Bearing Prognosis", "https://de.mathworks.com/help/predmaint/ug/wind-turbine-high-speed-bearing-prognosis.html", "doc"), res("exponentialdegradationmodel", "https://de.mathworks.com/help/predmaint/ref/exponentialdegradationmodel.html", "doc"), res("DigitalTwin Lectures PDF — Exercise 11", LECTURES_PDF, "doc")],
                52),
             task("d3-b5-t2", 3, 5, "16:15–17:30", "Exercise 12 — DRL Pong & Pump Feature Analysis", "🎮", "ML",
                "Exercise 12: Deep reinforcement learning — Playing Pong with DRL (File Exchange 87939) + pump diagnostics feature analysis (predmaint help). DRL: agent learns control policy through reward — different from supervised ML. Pump feature analysis: time-domain and frequency-domain features for fault classification — connects to PCA vibration monitoring (centrifuge example). For digital twin: DRL could optimise maintenance scheduling; feature analysis selects sensors for tower monitoring.",
                "Skim DRL Pong example — identify agent, environment, reward. Skim pump feature analysis — list 3 features (RMS, kurtosis, band energy). Write one sentence each: how DRL and feature analysis relate to digital twin operation phase.",
                ["DRL — agent/environment/reward", "Pump — 3 diagnostic features", "DRL vs supervised ML", "Feature analysis before ML training", "Digital twin operation phase link"],
                ["DRL concepts noted", "3 pump features listed", "Contrasted with supervised ML", "Connected to as-used twin", "Exercise 12 links saved"],
                [yt("HMOI_lkzW08", "StatQuest — Machine Learning Overview")],
                [res("MATLAB DRL Pong Example", "https://de.mathworks.com/matlabcentral/fileexchange/87939-playing-pong-with-deep-reinforcement-learning", "tool"), res("Pump Feature Analysis", "https://de.mathworks.com/help/predmaint/ug/analyze-and-select-features-for-pump-diagnostics.html", "doc"), res("DigitalTwin Lectures PDF — Exercise 12", LECTURES_PDF, "doc")],
                48)]),
        block(6, "17:30–20:00", "📡 Student Project — Antenna RUL Digital Twin",
            [task("d3-b6-t1", 3, 6, "17:30–18:45", "Project Narrative — Drone Pipeline & RUL Physics", "📡", "Project",
                "YOUR PROJECT (must be fluent): Industrial context — drone-based 2D imagery → 3D photogrammetric reconstruction of telecom towers (USA telecom client, ~€220K contract). Drone delivers GEOMETRY (as-built twin). Notebook adds PHYSICS — predictive RUL = true digital twin. Module: Modelling, Simulation and Digital Twin, Prof. Dr. Adele Nasti. Objective: predict Remaining Useful Life of 5G/6G telecom tower antenna under wind speed and operating temperature using DoE methodology (HEEDS-style MDAO). Value: predictive maintenance, fewer climber visits, reduced outages, lower OPEX.",
                "Practice 2-minute pitch WITHOUT slides: Problem → Approach → Results → Value. Drone pipeline FIRST (breadth), RUL model SECOND (depth). Answer: 'What is YOUR creative contribution?' → Combined industrial geometry pipeline with original physics-based RUL model and full DoE analysis.",
                ["2-minute pitch memorised", "Drone pipeline — what it provides", "RUL model — what it adds", "Creative contribution answer", "Business value — 3 bullets"],
                ["Pitch practiced aloud", "Industrial context numbers known", "Problem→approach→results flow", "Creativity answer ready", "Notebook intro reviewed"],
                [yt("9UpMeDO0A04", "Digital Twin Predictive Maintenance"), yt("9CcbYQ5QA70", "Rolls-Royce — Industrial DT Example")],
                [res("Your Antenna RUL Notebook", NOTEBOOK, "tool"), res("Liu et al. 2021 — UAV Photogrammetry Telecom", "https://doi.org/10.1016/j.autcon.2021.103780", "paper")],
                58),
             task("d3-b6-t2", 3, 6, "18:45–20:00", "RUL Formula, 40-Run DoE, Envelope & 9 References", "🧮", "Project",
                "RUL (days) = L_nom / (f_wind × f_temp × H_day). L_nom = 175,200 h ≈ 20 yr. f_wind(v) = (v/5)^1.6. f_temp(T) = 2^((T−20)/15). H_day = 24. SANITY: (5,20)→7300 d = 20 yr; (15,35)→629 d; (35,65)→41 d. DoE: 4 wind [5,15,25,35] × 10 temp [20…65] = 40 runs FULL FACTORIAL. Sensitivity: wind ≈ 3.5× temp. Operating envelope: wind≤12 m/s AND temp≤30°C → RUL>10 yr. NINE REFERENCES: (1) AIAA 2020, (2) Grieves & Vickers 2017, (3) Tao IEEE 2019, (4) Montgomery DoE, (5) Jardine prognostics, (6) Liu UAV photogrammetry, (7) Kapteyn 2021, (8) ISO/IEC 30173, (9) Siemens HEEDS 2024.",
                "Derive RUL formula on blank paper. Hand-calculate (5,20) and (35,65). Run notebook cells 4–16. For each of 9 references write one-sentence contribution. Build references slide.",
                ["RUL formula from memory", "RUL at (5,20) and (35,65) by hand", "40-run matrix — factor levels", "Wind/temp ratio ≈ 3.5×", "9 references with one-line contribution"],
                ["Formula derived on paper", "Sanity checks verified", "Notebook run complete", "9 refs with contributions", "Envelope limits memorised"],
                [yt("HvF_3Rok8RY", "HEEDS — Response Surface Review"), yt("_Rgue-7KDww", "DoE — 40-Run Factorial")],
                [res("Your Antenna RUL Notebook", NOTEBOOK, "tool"), res("AIAA 2020 Position Paper", AIAA, "paper"), res("Kapteyn 2021 — Nature Comp Sci", "https://doi.org/10.1038/s43588-021-00119-1", "paper")],
                65)]),
        block(7, "20:00–23:00", "📊 PCA, Surrogate & Final Mock Exam",
            [task("d3-b7-t1", 3, 7, "20:00–21:30", "PCA — Six Steps from Prof's Notes", "📊", "Surrogate",
                "PCA = unsupervised linear transformation identifying patterns via feature correlation. Uses: FEATURE EXTRACTION and DIMENSIONALITY REDUCTION ('reducing columns'). Avoid overfitting with sparse data. Mechanism: direction of MAXIMAL VARIANCE. Step 0: NORMALIZE data. Step 1: Covariance matrix — diagonal = variance (maximize), off-diagonal = covariance (→0, decorrelate). Step 2: Eigenvalues λ and eigenvectors v: det(T−λI)=0, Tv=λv. Step 3: Order eigenvalues descending. Step 4: Projection matrix P = (v⁽¹⁾…v⁽ᵏ⁾), size n×k. Step 5: Transform: (m×n) × (n×k) = (m×k). Centrifuge example: 20 vibration features → PC1=energy, PC2=imbalance, PC3=bearing.",
                "Execute PCA by hand on 3×2 toy dataset. List all 6 steps (0–5). Watch StatQuest and confirm each step. Practice 30-second PCA explanation. Exam answer: PCA is UNSUPERVISED — no labels needed.",
                ["List PCA steps 0–5", "Covariance diagonal vs off-diagonal", "Eigenvalue equation", "Matrix dimensions (m×n)×(n×k)", "Centrifuge 3 PC meanings"],
                ["6 steps from memory", "Toy PCA by hand", "StatQuest videos watched", "Unsupervised property known", "Connected to vibration monitoring"],
                [yt("FgakZw6K1QQ", "StatQuest — PCA Step-by-Step"), yt("HMOI_lkzW08", "StatQuest — PCA Main Ideas"), yt("_UVHneBUBW0", "StatQuest — PCA Full Walkthrough")],
                [res("DigitalTwin Lectures PDF — PCA Notes", LECTURES_PDF, "doc")],
                55),
             task("d3-b7-t2", 3, 7, "21:30–23:00", "Surrogate Models & Full Mock Exam", "🏆", "ALL",
                "SURROGATE MODEL (notes p.2 & p.4): dataset from high-fidelity model, approximated for faster runs. SURROGATE-BASED OPTIMISATION: optimise on surrogate (cheap), validate on high-fidelity model. Hierarchy: FEA (slow) → analytical RUL (medium) → response surface/ML (fast). AI in engineering: wing aerodynamics — ML predicts CFD lift/drag. FINAL MOCK EXAM: 15 min present + 10 min Q&A on ALL topics. Criteria: depth, breadth, creativity, literature, presentation. Drill 25 trap questions from Days 1–3. Presentation ≤12 min, 11 slides, demo notebook.",
                "Draw surrogate fidelity hierarchy for antenna project. Run full mock exam: present aloud 15 min, Q&A 10 min from random trap list. Record, review, fix weak answers. Sleep — memory consolidation matters.",
                ["Define surrogate model", "Define surrogate-based optimisation", "Draw fidelity hierarchy for antenna", "15-min mock presentation timed", "10-min Q&A — 5 random trap Qs answered"],
                ["Surrogate hierarchy drawn", "Mock exam recorded", "Weak answers fixed", "Presentation ≤12 min", "Confident for exam"],
                [yt("64N2BY747Cw", "High-Fidelity CFD Base Model"), yt("HvF_3Rok8RY", "HEEDS Surrogate Optimization"), yt("9CcbYQ5QA70", "Presentation Inspiration — Rolls-Royce")],
                [res("Your Antenna RUL Notebook", NOTEBOOK, "tool"), res("AIAA Digital Twin Definition & Value", AIAA, "paper"), res("DigitalTwin Lectures PDF", LECTURES_PDF, "doc")],
                65)]),
    ]
}

emit_day("day1", day1)
emit_day("day2", day2)
emit_day("day3", day3)

total = sum(len(b["tasks"]) for d in [day1, day2, day3] for b in d["blocks"])
print(f"Done — total tasks: {total}")
assert total == 42, f"Expected 42 tasks, got {total}"
