#!/usr/bin/env python3
"""Generate day1.ts, day2.ts, day3.ts for TwinBlitz curriculum."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src/lib/curriculum"

AIAA = "https://www.aiaa.org/docs/default-source/uploadedfiles/issues-and-advocacy/policy-papers/digital-twin-institute-position-paper-(december-2020).pdf"
ASME_UNCERT = "https://www.asme.org/codes-standards/find-codes-standards/ptc-19-1-test-uncertainty"
NASA_TRL = "https://www.nasa.gov/directorates/heo/scan/engineering/technology/technology_readiness_level"
HEEDS_GUIDE = "https://www.plm.automation.siemens.com/global/en/products/simcenter/HEEDS.html"

def yt(id_, title):
    return {"id": id_, "title": title}

def res(title, url, type_="doc"):
    return {"title": title, "url": url, "type": type_}

def task(id_, day, block, slot, title, emoji, category, learn, practice, exercises, checklist, youtube, resources, xp):
    return {
        "id": id_, "day": day, "block": block, "slot": slot, "title": title, "emoji": emoji,
        "category": category, "learn": learn, "practice": practice, "exercises": exercises,
        "checklist": checklist, "youtube": youtube, "resources": resources, "xp": xp,
    }

def block(n, slot, label, tasks):
    return {"block": n, "slot": slot, "label": label, "tasks": tasks}

def emit_day(name, plan):
    lines = ['import type { DayPlan } from "./types";', "", f"export const {name}: DayPlan = "]
    lines.append(json.dumps(plan, indent=2, ensure_ascii=False))
    lines[-1] = lines[-1].replace('"day"', 'day').replace('"date"', 'date')  # noop for ts
    # json is valid TS for object literals with quoted keys
    (OUT / f"{name}.ts").write_text("\n".join(lines) + ";\n", encoding="utf-8")
    print(f"Wrote {name}.ts — {sum(len(b['tasks']) for b in plan['blocks'])} tasks")

# ─── DAY 1 ───────────────────────────────────────────────────────────────────
day1 = {
  "day": 1, "date": "2026-06-08",
  "title": "Digital Twin Theory Foundations",
  "subtitle": "Prof. Nasti class notes pages 1–2 — definitions she will grill you on",
  "theme": "Master every definition before touching HEEDS or your project",
  "blocks": [
    block(1, "05:00–08:00", "📘 Digital Twin Core (your handwritten p.1)",
      [task("d1-b1-t1", 1, 1, "05:00–06:30", "Digital Twin Definition & 5-Stage Lifecycle", "🔄", "Theory",
        "Prof. Nasti's exact definition: 'The digital twin is the digital representation of a physical product throughout its lifecycle — the virtual product.' The engineering product lifecycle has FIVE stages connected in order: (1) Design & Analysis, (2) Manufacture, (3) Build & Assembly, (4) Experimental Testing, (5) Service. At EACH stage the digital twin lets you optimise and de-risk the real product by simulating behaviour for specific operating conditions. Feeding real operational data into a system-level simulation creates a unique virtual model per real product. CRITICAL exam trap: 'The digital twin does NOT replace experimental testing.' Simulation cost << experimental cost, but both are needed. The core is a fully coupled multi-disciplinary, multi-fidelity PARAMETRIC simulation model.",
        "Draw the 5-stage lifecycle arrow diagram from memory. Under each stage write ONE digital-twin use case (as-designed calibration, as-built factory simulation, as-used health monitoring). Say the definition aloud 3× without reading. Open AIAA position paper — find the three lifecycle stages they use (as-designed, as-built, as-used/maintained) and map them to Prof's 5 stages.",
        ["Recite the digital twin definition verbatim", "List all 5 lifecycle stages in order", "Name 3 as-designed / as-built / as-used use cases from AIAA paper", "Explain why DT does NOT replace experimental testing", "What sits at the core of every digital twin?"],
        ["Watch Rolls-Royce Intelligent Engine video", "Watch Siemens digital twin video", "Draw 5-stage lifecycle from memory", "Read AIAA Definition & Value paper intro", "Can explain DT to a non-expert in 60 seconds"],
        [yt("9CcbYQ5QA70", "Rolls-Royce — Pioneering the Intelligent Engine"), yt("ObGhB9CCHP8", "Siemens — Digital Twin"), yt("HftDI09LVI0", "ASME — Digital Twin Cities"), yt("9UpMeDO0A04", "Digital Twin Explained — Industry Overview")],
        [res("AIAA Digital Twin: Definition & Value (Dec 2020)", AIAA, "paper"), res("ISO/IEC 30173 Digital Twin Terminology", "https://www.iso.org/standard/77808.html", "doc")],
        50),
       task("d1-b1-t2", 1, 1, "06:30–08:00", "Virtual vs Real Product + Fidelity vs Accuracy", "⚖️", "Theory",
        "Your notes circle 'Accuracy VS Fidelity' — know the difference cold. FIDELITY = level of detail/realism in mirroring physical assets (can mean geometry fidelity OR model accuracy depending on context). ACCURACY = how close predictions are to reality (geometry, behaviour, dynamics). Trade-off: RUN TIME vs ACCURACY — higher fidelity models take longer. The product lifecycle introduces variations the twin must capture: manufacturing variations, assembly/build tolerances, product as-designed vs as-built, real operating conditions, aspects of physics NOT captured by simulation. Parametric geometry (CAD) lets you simulate as-designed AND as-manufactured. Geometry idealisation is always needed before simulation.",
        "Make a 2-column table: Fidelity vs Accuracy with 3 examples each. Draw virtual product ↔ real product diagram with arrows showing manufacturing variations, operating conditions, and missed physics. Explain the runtime-accuracy trade-off with a concrete example (coarse mesh = fast but less accurate).",
        ["Define fidelity in YOUR words (2 meanings)", "Define accuracy in YOUR words", "Draw virtual↔real product diagram with 4 variation sources", "Give example of runtime vs accuracy trade-off", "Why is parametric geometry essential?"],
        ["Understand fidelity vs accuracy distinction", "Draw virtual vs real diagram from notes", "Explain runtime-accuracy trade-off aloud", "Read lecture slide on geometry idealisation", "Can answer: 'What is fidelity?' without hesitation"],
        [yt("8u6dYTuBymA", "Ansys — Car Crash Simulation (fidelity example)"), yt("z_g-ov61DNw", "Building Ventilation CFD Simulation"), yt("cHThndE20oI", "Heat Transfer Simulation — Cup of Tea")],
        [res("NASA Systems Engineering Handbook", "https://www.nasa.gov/connect/ebooks/nasa-systems-engineering-handbook", "doc")],
        50)]),
    block(2, "08:00–11:00", "🔬 Modelling Approaches & I/O (handwritten p.2)",
      [task("d1-b2-t1", 1, 2, "08:00–09:30", "Physics-Based vs Empirical Modelling", "🧮", "Theory",
        "Two fundamental approaches: (1) PHYSICS-BASED — exploits laws of physics, starts from first principles, defines mathematical relationships governing system behaviour. (2) EMPIRICAL — starts from real-world observations/experimental data, uses statistical methods to extract behaviour. Physics-based suits simple/fully-understood physics. Empirical/data-driven suits data-rich problems (ML). In practice BOTH matter — even physics models need experimental validation. A model is a REPRESENTATION of reality; some physics may be missed or unknown → calibration fixes this. Models are characterised by INPUT-OUTPUT relationships. Typical INPUTS: geometric parameters (dimensions), operating conditions/constraints (ambient temperature), operating envelope. Typical OUTPUTS: measurable attributes (metal temperature), derived attributes (efficiency requiring post-processing).",
        "For the 5G antenna from your project: list 3 inputs and 3 outputs. For motorcycle traction control from class notes: list inputs (front/rear wheel speed, throttle, lean angle) and ideal responses. Classify each as physics-based or empirical: CFD, curve fitting, Arrhenius aging, neural network surrogate.",
        ["Define physics-based modelling", "Define empirical modelling", "List 3 typical inputs and 3 outputs for any model", "What is an operating envelope?", "When would you pick empirical over physics-based?"],
        ["Can define both modelling types", "Listed I/O for antenna project", "Listed I/O for traction control P-diagram", "Understand operating envelope concept", "Read physics vs empirical lecture slide"],
        [yt("64N2BY747Cw", "Rocket CFD Simulation"), yt("pcLg6C_WlHg", "Bridge Aeroelastic Flutter Simulation")],
        [res("Advanced Engineering Mathematics — Kreyszig", "https://www.bau.edu.jo/UserPortal/UserProfile/PostsAttach/59003_3812_1.pdf", "doc")],
        45),
       task("d1-b2-t2", 1, 2, "09:30–11:00", "Engineering Design Process + Model Coupling", "🔗", "Theory",
        "Design process is ITERATIVE: Idea → Conceptual Design → Preliminary Design → Detailed Design → Release for Manufacture. At each level: System → Subsystems → Components. Process automation & simulation-driven design are multidisciplinary, integrated, multi-fidelity. Risk level drives accuracy and fidelity needed. MODEL COUPLING (your notes): 'Solving two or more models together in an iterative loop, because one's outputs are others' inputs — INTERDEPENDENT, cannot be solved independently.' Example from notes — Smart Building HVAC: Occupancy↑ → Heat generation↑ → HVAC cooling demand↑ → Energy consumption↑. Models: Thermal, Occupancy, Airflow, Energy — coupled causal chain. Rolls-Royce seal example: seals sit at intersection of air system, thermal physics, flight loads.",
        "Draw the design process funnel (idea → release). Draw the HVAC coupling chain with 4 models and arrows. Explain in 3 sentences why coupled models need iterative loops. From your antenna project: what models would couple in a full tower digital twin (structural FEA + thermal + wind load + RUL prognostics)?",
        ["List 4 design process stages after 'idea'", "Define model coupling with the word 'interdependent'", "Draw HVAC coupling chain from class notes", "Why can't coupled models be solved independently?", "Give one coupling example from your antenna project"],
        ["Drew design process stages from memory", "Drew HVAC coupling diagram", "Can define model coupling verbatim", "Connected coupling to antenna project", "Watched coupled systems video"],
        [yt("9CcbYQ5QA70", "Rolls-Royce — Multi-disciplinary Engine (coupling context)")],
        [res("ASME GT2020 — Adele Nasti Seal Design Paper", "https://asmedigitalcollection.asme.org/GT/proceedings-abstract/GT2020/84188/V07CT14A023/1095072", "paper")],
        50)]),
    block(3, "11:00–14:00", "✅ Verification & Validation Deep Dive (exam traps)",
      [task("d1-b3-t1", 1, 3, "11:00–12:30", "Verification vs Validation — Know the Exact Wording", "✅", "V&V",
        "This is Prof. Nasti's favourite trap question. VERIFICATION: 'Have I done the maths right?' — checks software implementation against expected results from the algorithm. Aims for ZERO error in code. Applies to simulation software development. VALIDATION: 'Have I done the right maths?' — checks model predictions against real-world behaviour. Aims for ACCEPTABLE delta (subjective). Most common validation: against experimental test data OR against higher-fidelity model. Model CALIBRATION: adjusting internal model parameters to match experimental data — incorporates missed physics. DATA MATCHING = model calibration (your notes). Measurement uncertainty: e.g. d = 35.0 (±0.1) → manufacturing tolerance. ASME PTC 19.1 governs test uncertainty.",
        "Write on paper: Verification = ___ / Validation = ___. Create 3 exam-style Q&A cards. Example: 'You compare CFD to wind tunnel — is that V or V?' (Validation). 'You check FEA code against analytical beam solution — V or V?' (Verification). Practice saying answers in complete sentences — Prof fails vague answers.",
        ["State verification question ('Have I done the maths right?')", "State validation question ('Have I done the right maths?')", "Define model calibration", "What is data matching?", "What does ±0.1 mean in d=35.0(±0.1)?"],
        ["Memorised V vs V definitions word-for-word", "Created 5 V/V practice questions", "Can explain calibration vs validation", "Read ASME PTC 19.1 overview", "Practiced oral answers aloud"],
        [yt("9x9LYvErnwk", "Model Validation in Simulation")],
        [res("ASME PTC 19.1 — Test Uncertainty", ASME_UNCERT, "paper")],
        55),
       task("d1-b3-t2", 1, 3, "12:30–14:00", "Least Squares, Curve Fitting & Surrogate Intro", "📈", "V&V",
        "CURVE FITTING: generate curve as close to data as possible — empirical model creation. LEAST SQUARE METHOD: estimates model parameters by MINIMISING Σ(yᵢ − f(xᵢ))² — sum of squared residuals between measured data and model predictions. Used for model calibration/data matching. INTERPOLATION: prediction WITHIN measured boundaries. EXTRAPOLATION: prediction OUTSIDE known range (higher uncertainty). SURROGATE MODEL (your notes p.2 & p.4): dataset generated from high-fidelity model, approximated for faster runs. Surrogate-based OPTIMISATION: run optimisation on surrogate instead of expensive model, then return to main model for accurate solution. Geometry idealisation levels: simplified 3D, 2D slice, 1D vector — all must stay in sync with master CAD model.",
        "On paper: write the least-squares formula Σ(yᵢ−f(xᵢ))² and explain each term. Fit a line by hand to 3 data points. Explain when interpolation is safe vs when extrapolation is dangerous. For your antenna RUL model: is it physics-based or surrogate? (Physics-based analytical — but could have surrogate wrapper for full FEA).",
        ["Write least-squares residual formula", "Define interpolation vs extrapolation", "Define surrogate model from your notes", "What is surrogate-based optimisation?", "Name 3 geometry idealisation levels"],
        ["Wrote least-squares formula from memory", "Can explain interpolation vs extrapolation", "Defined surrogate model clearly", "Linked to antenna RUL model type", "Understand geometry idealisation levels"],
        [yt("_UVHneBUBW0", "StatQuest — PCA Step-by-Step (math foundation)")],
        [res("Kreyszig Ch.22 — Least Squares / Optimization", "https://www.bau.edu.jo/UserPortal/UserProfile/PostsAttach/59003_3812_1.pdf", "doc")],
        50)]),
    block(4, "14:00–17:00", "🏗️ Digital Twin Stages & Integrated Design",
      [task("d1-b4-t1", 1, 4, "14:00–15:30", "As-Designed / As-Built / As-Used Stages", "🏭", "Theory",
        "Your handwritten p.6 notes three twin stages: AS-DESIGNED — before physical object exists (3D CAD, material properties). AS-BUILT — after manufacturing (manufacturing records, QC, BOM). AS-USED/MAINTAINED — during operation (live sensor data, temperature, power output). AIAA adds use cases per stage: As-designed → calibration, performance monitoring, design optimisation. As-built → factory simulation, material & process modelling. As-used → health monitoring, condition-based maintenance, failure analysis, anomaly detection, end-of-life decisions. Your antenna project spans: drone photogrammetry (as-built geometry) + RUL model (as-used predictive maintenance).",
        "Map your antenna project to all 3 stages with specific data sources. Draw a timeline: design → manufacture → deploy → operate showing what data feeds the twin at each point. Prepare 30-second explanation for Prof: 'Where does my project sit in the lifecycle?'",
        ["Define as-designed, as-built, as-used", "List 3 use cases per stage from AIAA", "Map antenna project to all 3 stages", "What data feeds as-used twin for antenna?", "How does drone 3D scan fit in?"],
        ["Mapped project to 3 twin stages", "Read AIAA use case table", "Prepared lifecycle explanation", "Understand as-built vs as-designed", "Can explain predictive maintenance"],
        [yt("ObGhB9CCHP8", "Siemens Digital Twin — Lifecycle"), yt("HftDI09LVI0", "Digital Twin Cities — ASME")],
        [res("AIAA Digital Twin Definition & Value", AIAA, "paper"), res("Grieves & Vickers 2017 — Digital Twin Springer", "https://link.springer.com/chapter/10.1007/978-3-319-38756-4_36", "paper")],
        50),
       task("d1-b4-t2", 1, 4, "15:30–17:00", "Process Automation & Integrated Design Systems", "⚙️", "HEEDS",
        "PROCESS AUTOMATION (your notes p.2): brings the design process itself into software — links multiple simulation tools via automated data transfers = INTEGRATED DESIGN SYSTEMS (simulation framework). Benefits: speed up process, improve product attributes. This is exactly what HEEDS + iSight do. Software tools from your notes: CAD=NX, FEA=Ansys/Abaqus/Nastran, contact=LS-Dyna, mesh-free=Simsolid, automation=HyperWorks, OPTIMISATION=HEEDS+iSight. HEEDS = Multi-disciplinary design exploration — Design of Experiments + optimisation + process automation in one workflow. Prof connects this to Rolls-Royce seal optimisation (ASME GT2020 paper she authored).",
        "List all 8 software tools from your class notes with their purpose. Explain process automation in one sentence. Open HEEDS getting started guide — identify: Design Space, Response Surface, Optimisation workflow. Connect: your antenna DoE notebook IS a manual version of what HEEDS automates.",
        ["Define process automation from notes", "What are Integrated Design Systems?", "List HEEDS + iSight purpose", "Name 4 FEA tools from notes", "How does your notebook relate to HEEDS?"],
        ["Listed all software tools from notes", "Read HEEDS getting started guide intro", "Can explain process automation", "Connected notebook to HEEDS workflow", "Watched HEEDS overview video"],
        [yt("HvF_3Rok8RY", "HEEDS — Multi-Disciplinary Design Exploration"), yt("SwgtZp4Jcjs", "Isight — Process Automation Overview")],
        [res("HEEDS Product Page — Siemens", HEEDS_GUIDE, "doc"), res("HEEDS Getting Started Guide PDF", "/Users/msv/Downloads/HEEDSGettingStartedGuide.pdf", "doc"), res("ASME GT2020 Nasti Seal Paper", "https://asmedigitalcollection.asme.org/GT/proceedings-abstract/GT2020/84188/V07CT14A023/1095072", "paper")],
        55)]),
    block(5, "17:00–20:00", "📐 Functional Modeling Preview (motorcycle notes)",
      [task("d1-b5-t1", 1, 5, "17:00–18:30", "Functional Modeling + Motorcycle Traction FFD", "🏍️", "Functional",
        "FUNCTIONAL MODELLING: technique to capture key functionalities of a system and their interactions — abstraction to understand relationships and identify improvements. Your class notes — Racing Motorcycle Traction Control FFD: Goals: protect rider, communicate grip level (maximize grip crossed out!). Section 1.0 Monitor: sliding, lean angle, steering angle, brake pressure, suspension state, track position. Compare user settings: engine braking, allowed lean, interference level, power mode, suspension. Change outputs: throttle, fueling, lean, steering, brakes, suspension behaviour. Make prediction: further track layout, traction level. Feedback loop arrow from prediction back to compare/adjust. This is a FUNCTIONAL FLOW DIAGRAM — NOT software architecture.",
        "Redraw the motorcycle FFD from your handwritten notes from memory. For each of the 4 columns write 1 sentence explaining data flow. Prof may ask: 'Is functional modelling the same as software architecture?' Answer: NO — it's an abstraction of the real problem. Prepare this answer.",
        ["Define functional modelling", "Redraw motorcycle traction FFD from memory", "List all 6 monitored inputs (Section 1.0)", "List all 6 adjustable outputs", "What does the prediction feedback loop do?"],
        ["Redrew FFD from handwritten notes", "Can define functional modelling", "Know exam trap: FFD ≠ software architecture", "Listed all inputs and outputs", "Explained feedback loop"],
        [yt("8u6dYTuBymA", "Simulation-Driven Design Context")],
        [res("NASA Systems Engineering — Functional Analysis", "https://www.nasa.gov/connect/ebooks/nasa-systems-engineering-handbook", "doc")],
        45),
       task("d1-b5-t2", 1, 5, "18:30–20:00", "P-Diagram — Rear Wheel Traction Control", "📊", "Functional",
        "P-DIAGRAM (Parameter Diagram) from your notes: Center process = 'Regulate rear wheel traction.' INPUTS (left): front wheel speed, rear wheel speed, throttle position, engine speed, lean angle. NOISE FACTORS (top): road conditions, tire wear/pressure, temperature, load, sudden inputs. CONTROL FACTORS (bottom): allowed slip, TC sensitivity level, torque reduction limits. IDEAL RESPONSE (top-right): traction maintained, smooth torque delivery, stable vehicle, minimal impact on inputs. ERROR STATE (bottom-right): excessive rear slip, jerky throttle, unstable vehicle, TC too late. 4-step operational flow from notes: (1) Sense operating conditions, (2) Evaluate traction level (calculate slip, compare threshold), (3) Control available forces (reduce input, limit power), (4) Provide system feedback (indicator, log data).",
        "Draw the complete P-diagram from memory with all 5 zones. Write the 4-step L0-L2 operational flow. Practice explaining: 'What is a noise factor vs control factor?' — Noise = uncontrolled environment; Control = what the system can tune.",
        ["Draw P-diagram with all 5 zones from memory", "List 4-step operational flow L0-L2", "Define noise factors (3 examples)", "Define control factors (3 examples)", "Ideal response vs error state — 2 examples each"],
        ["Drew P-diagram from handwritten notes", "Memorised 4-step operational flow", "Can explain noise vs control factors", "Practiced oral explanation", "Compared P-diagram to FFD"],
        [],
        [res("AIAG/VDA FMEA Handbook (P-diagram context)", "https://www.aiag.org/quality/automotive-core-tools", "doc")],
        50)]),
    block(6, "20:00–23:00", "🎯 Day 1 Boss — Oral Exam Drill",
      [task("d1-b6-t1", 1, 6, "20:00–21:30", "Day 1 Flashcard Oral Exam — All Definitions", "🎤", "ALL",
        "Prof. Nasti fails vague answers on the LAST attempt. Drill every Day 1 definition as a complete sentence answer. Key phrases she expects: 'digital representation throughout lifecycle', 'does not replace experimental testing', 'Have I done the maths right?' vs 'Have I done the right maths?', 'iterative loop' for coupling, 'interdependent', 'operating envelope', 'first principles' vs 'observations from real world'. Time yourself: 60 seconds per definition. If you hesitate, restart.",
        "Record yourself answering 15 questions aloud. Play back — flag any 'um' or incomplete sentences. Write perfect answers for: What is a digital twin? What is model coupling? Verification vs validation? Physics vs empirical? What is process automation?",
        ["Answer 'What is a digital twin?' in 30 seconds", "Answer V vs V without mixing them up", "Define model coupling with 'interdependent'", "Explain fidelity vs accuracy", "List 5 lifecycle stages in order"],
        ["Recorded 15 oral answers", "Fixed all hesitant definitions", "Wrote perfect answer sheet", "Practiced with timer", "Ready for Prof's definition traps"],
        [yt("9CcbYQ5QA70", "Rolls-Royce — Review intelligent engine context"), yt("ObGhB9CCHP8", "Siemens DT — Review lifecycle")],
        [res("DigitalTwin Exam Guidelines PDF", "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Exam_Guidelines.pdf", "doc")],
        60),
       task("d1-b6-t2", 1, 6, "21:30–23:00", "Day 1 Written Drill — Exercises from Lecture PDF", "📝", "ALL",
        "Complete AIAA Exercise 1 from lecture slides: (1) What digital twin use case has value for a company? (2) What products could have a digital twin? (3) Ideas for final exam. Your answer for (1): predictive maintenance of telecom infrastructure using drone-derived geometry + physics-based RUL — saves climber visits, reduces outages. For (2): aero engines, smart buildings, racing motorcycles, centrifuges, injection molding machines. Review Technology Readiness Levels — NASA 1-9 scale. Your project is roughly TRL 4-5 (validated in lab/simulation, not yet deployed at scale).",
        "Write full answers to all 3 AIAA exercise questions. Read NASA TRL page and justify TRL 4-5 for your project. Draft your 200-word value proposition paragraph for the presentation.",
        ["Answer AIAA Exercise 1 three questions in writing", "Define TRL and place your project on scale", "Write 200-word 'why my use case matters' paragraph", "List 5 references for presentation", "Review exam criteria: depth, breadth, creativity"],
        ["Completed AIAA exercise answers", "Know TRL level for project", "Wrote use-case value paragraph", "Read exam guidelines completely", "Listed presentation references"],
        [yt("9UpMeDO0A04", "Digital Twin Use Cases Overview")],
        [res("DigitalTwin Exam Guidelines", "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Exam_Guidelines.pdf", "doc"), res("NASA TRL Scale", NASA_TRL, "doc"), res("DigitalTwin Lectures Exercises PDF", "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Lectures_Exercises.pdf", "doc")],
        55)]),
  ]
}

day2 = {
  "day": 2, "date": "2026-06-09",
  "title": "DoE, Optimization & HEEDS Mastery",
  "subtitle": "Class notes p.3–5 + Prof's lecture slides 102–120 — she loves Pareto questions",
  "theme": "Design space exploration, sensitivity, and the HEEDS workflow",
  "blocks": [
    block(1, "05:00–08:00", "🧪 Design of Experiments — Theory (handwritten p.3)",
      [task("d2-b1-t1", 2, 1, "05:00–06:30", "DoE Definition & Four Types", "🧪", "DoE",
        "DESIGN OF EXPERIMENTS (DoE): tool to explore design space and understand sensitivity of inputs on outputs — run multiple configurations of a model, gather data. Your notes list 4 types: (1) FULL FACTORIAL — all combinations of all parameter levels; estimates all main effects AND interactions; computationally expensive. (2) FRACTIONAL FACTORIAL — derivative of full factorial; less info, more efficient. (3) SCREENING EXPERIMENTS — many parameters, few runs, low cost, identifies key variables. (4) LATIN HYPERCUBE — optimised choice of runs; captures non-linear effects with fewer runs. Design matrix: columns = inputs (in1, in2, in3), column = output (out1). Prof's injection molding example: inputs = temperature, injection pressure, cooling time; outputs = part weight, dimensional deviation, surface quality, cycle time.",
        "Build a design matrix on paper for injection molding with 3 inputs at 2 levels each (2³=8 runs). Identify which DoE type you'd use for: (a) 2 factors, budget for 16 runs → full factorial, (b) 20 factors, budget for 30 runs → screening. Your antenna project uses FULL FACTORIAL: 4 wind × 10 temp = 40 runs.",
        ["Define DoE in Prof's words", "List all 4 DoE types with trade-offs", "What is a design matrix?", "Injection molding example — 3 inputs, 4 outputs", "Why did you pick full factorial for antenna?"],
        ["Can define DoE clearly", "Listed all 4 types with pros/cons", "Built design matrix on paper", "Know injection molding example", "Justified full factorial for 40-run DoE"],
        [yt("_Rgue-7KDww", "JMP — Design of Experiments Process"), yt("PD_0QjEyQJk", "Minitab — DoE Introduction")],
        [res("Montgomery — Design and Analysis of Experiments", "https://www.wiley.com/en-us/Design+and+Analysis+of+Experiments%2C+9th+Edition-p-9781119493918", "doc")],
        50),
       task("d2-b1-t2", 2, 1, "06:30–08:00", "Sensitivity Analysis & Pareto Charts", "📊", "DoE",
        "SENSITIVITY ANALYSIS: studies how changes in input parameters affect model output. Method from your antenna notebook: sweep one factor across full range while holding other at midpoint — larger Δoutput = more sensitive factor. PARETO CHART (from notes + lecture): ranks factors by impact on output — 'sensitivity towards output.' In your project: wind sweep (5→35 m/s at temp=42.5°C) gave larger RUL reduction than temp sweep (20→65°C at wind=20 m/s) — wind is DOMINANT (~3.5× impact). Pareto chart shows this visually. Also know: main effects plots, interaction plots, parallel axes plots (from lecture slide 106).",
        "Recalculate sensitivity from your notebook: Δwind and Δtemp. Draw a Pareto bar chart on paper. Explain in 2 sentences why Pareto matters for robust design: 'Understanding sensitivity is crucial to design robust products.'",
        ["Define sensitivity analysis", "What does a Pareto chart show?", "Which factor dominates in your antenna project?", "What is a main effects plot?", "Recalculate Δwind and Δtemp from RUL formula"],
        ["Recalculated sensitivity deltas", "Drew Pareto chart on paper", "Wind identified as dominant factor", "Watched DoE post-processing videos", "Can explain Pareto to Prof"],
        [yt("9x9LYvErnwk", "DoE with FEA — Abaqus/Isight Example"), yt("V_yaMyLeJ1I", "Isight Plugin within Abaqus CAE")],
        [res("Abaqus DoE Results Graphs", "https://abaqus-docs.mit.edu/2017/English/IhrUserMap/ihr-c-Results-GraphSpecialized.htm", "doc")],
        55)]),
    block(2, "08:00–11:00", "⚙️ HEEDS & Process Automation Deep Dive",
      [task("d2-b2-t1", 2, 2, "08:00–09:30", "HEEDS Workflow — MDAO in Practice", "⚙️", "HEEDS",
        "HEEDS = Siemens Simcenter solution for Multi-Disciplinary Design Exploration. Automates: Design Space definition → DoE execution → Response surface → Optimisation. Same workflow you did manually in Python for antenna RUL. HEEDS connects to: Ansys, Abaqus, NX, Nastran, Excel, Python scripts, etc. Process automation = linking tools with automated data transfer (your notes: HEEDS + iSight). Prof's industrial case (slide 110): design optimisation of BOP for fatigue in HPHT environment using Isight + fe-safe. Your notebook IS the exam demo — you wrote the code, ran the DoE, produced Pareto + response surface + operating envelope.",
        "Open your DigitalTwin_Antenna_RUL.ipynb. For each HEEDS step, point to the equivalent notebook cell: (1) Design space = WIND_LEVELS × TEMP_LEVELS, (2) DoE execution = nested for loop, (3) Response surface = 3D plot_surface, (4) Optimisation/envelope = contour plot at 10yr RUL. Practice saying: 'I replicated the HEEDS workflow in Python because...'",
        ["What does HEEDS automate?", "Map 4 HEEDS steps to your notebook cells", "What is MDAO?", "Prof's industrial case slide 110 topic", "Why Python instead of HEEDS GUI?"],
        ["Opened and reviewed full notebook", "Mapped HEEDS steps to notebook", "Watched HEEDS overview video", "Read HEEDS getting started guide", "Can present workflow to Prof"],
        [yt("HvF_3Rok8RY", "HEEDS — Multi-Disciplinary Design Exploration"), yt("SwgtZp4Jcjs", "Isight — Process Automation")],
        [res("HEEDS — Siemens Simcenter", HEEDS_GUIDE, "doc"), res("Simulia Isight Brochure", "https://www.3ds.com/fileadmin/PRODUCTS-SERVICES/SIMULIA/RESOURCES/simulia-isight-brochure.pdf", "doc"), res("Your Antenna RUL Notebook", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb", "tool")],
        60),
       task("d2-b2-t2", 2, 2, "09:30–11:00", "Mesh Convergence & FEA Tools (handwritten p.5)", "🔧", "Tools",
        "MESH CONVERGENCE STUDY (your notes): progressively refine mesh to find sensitivity towards solution. Steps: (1) coarse mesh, (2) systematic refinement, (3) simulation iterations, (4) check convergence. Software from notes: CAD=NX, Dynamic=NX/MSC Nastran, General FEA=Ansys/Abaqus, Contact friction=LS-Dyna, Mesh-free=Simsolid, Automation=HyperWorks/HyperMesh, Optimisation=HEEDS+iSight. FMEA table structure from notes: Process, Failure Mode, Failure Effect, SEVERITY, Cause, OCCURRENCE, Current controls, DETECTION, TOTAL. Line-on-line interference → almost no wear (from notes).",
        "Write the 4 mesh convergence steps from memory. For your antenna project: you used an analytical model (no mesh) — explain to Prof WHY and when you'd need FEA instead. Fill one FMEA row for 'antenna structural failure due to wind fatigue'.",
        ["List 4 mesh convergence steps", "Name 6 simulation software tools from notes", "When is analytical model enough vs FEA needed?", "Fill one FMEA table row for antenna", "What is Simsolid (mesh-free FEA)?"],
        ["Memorised mesh convergence steps", "Listed all software tools", "Prepared FEA vs analytical justification", "Completed FMEA example row", "Understand Simsolid concept"],
        [yt("8u6dYTuBymA", "Ansys Simulation Example"), yt("z_g-ov61DNw", "CFD Simulation — Convergence Context")],
        [res("Ansys Meshing Best Practices", "https://www.ansys.com/resource-center/body-of-knowledge/meshing", "doc")],
        45)]),
    block(3, "11:00–14:00", "🎯 Design Optimization & Pareto Front",
      [task("d2-b3-t1", 2, 3, "11:00–12:30", "Design Optimization — Objectives, Constraints, Variables", "🎯", "Optimization",
        "DESIGN OPTIMISATION: computational technique to find best design given objectives and constraints through iterative search. Your notes: 'Swapping inputs & outputs — give target and ask model for inputs.' Can be component or system level. MULTI-OBJECTIVE: often conflicting objectives. Examples from notes: (1) Seal — lowest leakage, mass ≤ x kg. (2) Mug — max insulation, cost constraint. (3) Engine — min specific fuel consumption within safety margins. (4) Leaf seal — lowest leakage AND min heat at interface. Logistics example from notes: minimise delivery time + fuel cost; variables=routes/order; constraints=visit each customer once, fuel capacity, working hours.",
        "Write the optimisation problem statement for your antenna: OBJECTIVE = maximise RUL (or minimise degradation rate). VARIABLES = wind speed exposure, operating temperature. CONSTRAINTS = structural safety, data rate requirements. Compare to logistics example structure.",
        ["Define design optimisation", "Optimization vs DoE — what's the difference?", "Write optimisation problem for antenna project", "Logistics example — objectives, variables, constraints", "What is multi-objective optimisation?"],
        ["Defined optimisation clearly", "Wrote antenna optimisation problem", "Know logistics example from notes", "Understand objectives vs constraints", "Can explain 'swap inputs and outputs'"],
        [yt("HvF_3Rok8RY", "HEEDS — Optimization Workflow")],
        [res("Kreyszig Ch.22 — Gradient Method / Optimization", "https://www.bau.edu.jo/UserPortal/UserProfile/PostsAttach/59003_3812_1.pdf", "doc")],
        50),
       task("d2-b3-t2", 2, 3, "12:30–14:00", "Pareto Front, Global vs Local Minimum", "📉", "Optimization",
        "PARETO FRONT (your notes p.3): collection of optimal solutions between CONFLICTING objectives — feasible vs unfeasible designs, boundary = Pareto front. Example: stress vs mass — you cannot minimise both simultaneously; Pareto front shows trade-off curve. GLOBAL MINIMUM vs LOCAL MINIMUM: the challenge of optimisation is finding the GLOBAL minimum (absolute best). Local minimum may be 'good enough' in some engineering problems. Method of steepest descent (gradient method) from Kreyszig Ch.22. CATEGORICAL VARIABLE (notes): discrete values. UNCERTAINTY QUANTIFICATION (notes): nominal value + distribution variation.",
        "Sketch stress-vs-mass Pareto front with feasible cloud and boundary line. Mark a local minimum and global minimum on a 1D curve. For antenna: is wind-vs-temp a Pareto trade-off? (No — they're degradation drivers, not conflicting design objectives. But operating envelope IS a constraint boundary.)",
        ["Define Pareto front with 'conflicting objectives'", "Global vs local minimum — explain", "Sketch Pareto front stress vs mass", "Define categorical variable", "Define uncertainty quantification from notes"],
        ["Drew Pareto front sketch", "Explained global vs local minimum", "Know categorical variable definition", "Understand UQ definition", "Can distinguish DoE from optimisation"],
        [yt("9x9LYvErnwk", "Optimization + DoE in Simulation")],
        [res("Computational Approaches for Aerospace Design — Keane", "https://books.google.de/books?id=dMeitxe-ilgC", "doc")],
        55)]),
    block(4, "14:00–17:00", "🎲 Uncertainty, Monte Carlo & Pugh Matrix",
      [task("d2-b4-t1", 2, 4, "14:00–15:30", "Monte Carlo & Uncertainty Propagation", "🎲", "DoE",
        "MONTE CARLO (your notes p.7): computational technique using RANDOM SAMPLING for complex deterministic problems (e.g. multi-objective optimisation). Each input gets a PROBABILITY DISTRIBUTION (Gaussian or rectangular) → stochastic set of inputs → many deterministic runs. Useful for highly coupled physics or many input uncertainties. UNCERTAINTY QUANTIFICATION: identify sources, estimate input uncertainties, propagate to output uncertainties. Types: statistical (random noise) vs systematic (bias/offset from test setup). Propagation: x₁±δx₁ → effect on R; combined via ROOT SUM SQUARE (RSS). Robust design = low sensitivity of outputs to input variation.",
        "Explain Monte Carlo in 3 sentences. Give example: wind speed follows Weibull distribution at tower site → sample 1000 values → run RUL model 1000 times → get RUL distribution. Define 'stochastic set of inputs' from your notes.",
        ["Define Monte Carlo method", "What is a stochastic set of inputs?", "Statistical vs systematic uncertainty", "What is root sum square combination?", "What makes a design 'robust'?"],
        ["Defined Monte Carlo clearly", "Explained stochastic inputs", "Know UQ types", "Understand RSS combination", "Connected to antenna wind variability"],
        [yt("PD_0QjEyQJk", "Statistical Methods — Minitab Context")],
        [res("Moffat — Experimental Uncertainty Paper", "http://fluidos-lfa.usuarios.rdc.puc-rio.br/metexp-pos/Paper_Moffat.pdf", "paper")],
        50),
       task("d2-b4-t2", 2, 4, "15:30–17:00", "Pugh Matrix & Data Matching", "📋", "Functional",
        "PUGH MATRIX (your notes p.5): decision-making tool to compare multiple concepts against criteria by scoring them. Use when choosing between design alternatives early in conceptual design. DATA MATCHING = MODEL CALIBRATION (your notes p.3) — tuning parameters to match experimental data. Example from lecture: calibrate simulation models using experimental test results. For your project: calibrating f_wind exponent (1.6) and Arrhenius coefficient (15°C doubling) would require field failure data — acknowledge this as limitation/future work in presentation.",
        "Create a 3-concept × 5-criteria Pugh matrix for antenna monitoring approaches: (A) periodic climber inspection, (B) drone photogrammetry only, (C) full digital twin with RUL. Score +/−/S (same). Identify winner. Write 2 sentences on calibration limitations of your RUL model.",
        ["Define Pugh matrix purpose", "Data matching = what?", "Create Pugh matrix for 3 monitoring concepts", "What parameters would you calibrate in RUL model?", "Acknowledge model limitations for Prof"],
        ["Defined Pugh matrix", "Created 3×5 Pugh matrix", "Know data matching = calibration", "Identified RUL calibration limits", "Prepared honest limitation statement"],
        [],
        [res("Pugh Matrix — Concept Selection", "https://www.designsociety.org/publication/28700/design_studies", "paper")],
        45)]),
    block(5, "17:00–20:00", "🤖 Surrogate Models & AI in Engineering",
      [task("d2-b5-t1", 2, 5, "17:00–18:30", "Surrogate Models & Surrogate-Based Optimization", "🤖", "Surrogate",
        "SURROGATE MODEL (notes p.2 & p.4): dataset from high-fidelity model, approximated for faster runs. SURROGATE-BASED OPTIMISATION: optimise on surrogate (cheap), then validate on high-fidelity model. AI IN ENGINEERING (notes p.7): Wing aerodynamics — inputs=wing geometry, outputs=lift/drag coefficients; AI predicts CFD results faster with acceptable accuracy. ML as surrogate on simulation datasets — particularly for optimisation loops needing thousands of runs. Your analytical RUL model is already a low-fidelity surrogate of full FEA fatigue analysis — explain this hierarchy to Prof.",
        "Draw surrogate hierarchy: FEA (high-fidelity, slow) → analytical RUL (medium) → response surface (fast). Explain when you'd add ML on top. Answer: 'Could you replace your RUL model with ML?' — Yes but need training data from FEA/experiments, lose physics interpretability.",
        ["Define surrogate model", "Define surrogate-based optimisation", "Wing aerodynamics AI example — inputs/outputs", "Is your RUL model a surrogate? Of what?", "ML surrogate pros and cons"],
        ["Defined surrogate model clearly", "Drew fidelity hierarchy", "Know wing aerodynamics example", "Justified analytical model choice", "Can answer ML replacement question"],
        [yt("64N2BY747Cw", "CFD Simulation — High-Fidelity Base Model")],
        [res("Tao et al. 2019 — Digital Twin in Industry (IEEE)", "https://ieeexplore.ieee.org/document/8477107", "paper")],
        50),
       task("d2-b5-t2", 2, 5, "18:30–20:00", "Agile & Software Development Cycle", "🔄", "Tools",
        "AGILE (notes p.7): iterative and incremental project management — flexibility, customer collaboration, rapid value delivery. Key contrast to waterfall. SOFTWARE DEV CYCLE (notes p.5): (1) Planning, (2) Analysis, (3) Design, (4) Implementation, (5) Testing & integration, (6) Maintenance. Homework reference: Paper slide 204. For simulation software: VERIFICATION happens in Testing phase. Connect: your Jupyter notebook development followed stages — Planning (objective), Analysis (RUL physics), Design (DoE matrix), Implementation (Python code), Testing (sanity checks at 5/15/35 m/s), Maintenance (extend with real sensor data).",
        "List 6 software dev cycle stages from memory. Map your notebook development to each stage. Define Agile in one sentence. Prof may ask: 'How is simulation software development different from app development?' — Answer: verification against analytical solutions is critical.",
        ["List 6 software development stages", "Define Agile from notes", "Map notebook to 6 stages", "Where does verification fit in dev cycle?", "Agile vs waterfall — one difference"],
        ["Memorised 6 dev cycle stages", "Mapped notebook to stages", "Defined Agile", "Know verification in testing phase", "Prepared Agile answer"],
        [],
        [res("Agile Manifesto", "https://agilemanifesto.org/", "doc")],
        40)]),
    block(6, "20:00–23:00", "🎯 Day 2 Boss — DoE + HEEDS Oral Exam",
      [task("d2-b6-t1", 2, 6, "20:00–21:30", "DoE & HEEDS Oral Drill — Professor Trap Questions", "🎤", "ALL",
        "High-probability Prof questions Day 2: 'What is a full factorial DoE?' 'Why not screening for your antenna?' 'What is a Pareto chart?' 'Explain HEEDS workflow.' 'What is the dominant factor in your project?' 'Global vs local minimum?' 'Monte Carlo — when do you use it?' Practice PERFECT answers: Full factorial = all combinations, 4×10=40 runs. Screening = when many factors, few runs. Pareto = ranks factor impact. Dominant = wind speed (~3.5× temperature). HEEDS = automates DoE+optimisation across tools.",
        "30-minute oral drill with timer. Answer each question in ≤45 seconds with NO filler words. Record and review. Write backup answers for: 'Why full factorial?' → Only 2 factors, 40 runs is cheap for analytical model, captures all interactions.",
        ["Answer: What is full factorial DoE?", "Answer: Dominant factor in antenna project?", "Answer: HEEDS vs manual Python workflow?", "Answer: Pareto front vs Pareto chart?", "Answer: When to use Monte Carlo?"],
        ["Completed 30-min oral drill", "Recorded and reviewed answers", "Wrote perfect answer sheet", "No filler words in definitions", "Ready for DoE/HEEDS questions"],
        [yt("HvF_3Rok8RY", "HEEDS Review"), yt("_Rgue-7KDww", "DoE Process Review")],
        [res("Your Antenna RUL Notebook", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb", "tool")],
        60),
       task("d2-b6-t2", 2, 6, "21:30–23:00", "Re-run Antenna Notebook + Annotate Every Cell", "💻", "Project",
        "Open DigitalTwin_Antenna_RUL.ipynb. Run ALL cells. Annotate in your notes what EACH cell proves: Cell 4 = RUL formula, Cell 6 = 40-run design matrix, Cell 8 = RUL vs temp curves, Cell 10 = 3D response surface, Cell 12 = sensitivity deltas, Cell 14 = Pareto bar chart, Cell 16 = operating envelope contours. Know exact numbers: RUL at (5m/s, 20°C)=7300 days=20 years. RUL at (35m/s, 65°C)=41 days. Wind/temp ratio≈3.5×. Recommended ops: wind≤12 m/s, temp≤30°C → RUL>10 years.",
        "Run notebook end-to-end. Write a 1-sentence explanation per cell. Memorise the 3 RUL sanity-check numbers. Be able to derive RUL formula from scratch on paper: RUL = L_nom / (f_wind × f_temp × 24).",
        ["Run all notebook cells successfully", "RUL at (5,20) = ? days", "RUL at (35,65) = ? days", "Wind/temp impact ratio = ?", "Recommended operating point = ?"],
        ["Ran full notebook", "Annotated every cell", "Memorised 3 key RUL numbers", "Can derive formula on paper", "Know operating envelope recommendation"],
        [],
        [res("DigitalTwin_Antenna_RUL.ipynb", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb", "tool"), res("DigitalTwin_Antenna_RUL.pptx", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.pptx", "doc")],
        60)]),
  ]
}
emit_day("day2", day2)

day3 = {
  "day": 3, "date": "2026-06-10",
  "title": "PCA, Project Mastery & Exam Presentation",
  "subtitle": "Handwritten p.4 PCA + your Antenna RUL project + 10-min presentation prep",
  "theme": "Close every gap — theory, code, and presentation",
  "blocks": [
    block(1, "05:00–08:00", "📊 PCA — Step by Step (handwritten p.4)",
      [task("d3-b1-t1", 3, 1, "05:00–06:30", "PCA Theory — All 6 Steps from Your Notes", "📊", "Surrogate",
        "PCA = unsupervised linear transformation identifying patterns via feature correlation. Primary uses: FEATURE EXTRACTION and DIMENSIONALITY REDUCTION ('reducing columns'). Why: avoid overfitting / too many parameters with sparse data. Mechanism: find direction of MAXIMAL VARIANCE. Your notes Step 0: NORMALIZE data. Step 1: Covariance matrix → diagonal = variance (maximize), off-diagonal = covariance (→0, decorrelate). Step 2: Find eigenvalues λ and eigenvectors v: det(T−λI)=0, Tv=λv. Step 3: Order eigenvalues descending (change reference frame). Step 4: Projection matrix P = (v⁽¹⁾, v⁽²⁾, ... v⁽ᵏ⁾), size n×k. Step 5: Transform: Old dataset (m×n) × P (n×k) = new dataset (m×k).",
        "Execute PCA by hand on a 3×2 toy dataset (3 samples, 2 features). Show covariance matrix, eigenvalues, projection. Then watch StatQuest and confirm each step matches your notes. Prof's centrifuge example: 20 vibration features → PCA1=overall energy, PCA2=imbalance, PCA3=bearing patterns.",
        ["List all 6 PCA steps (0-5)", "What goes on covariance diagonal vs off-diagonal?", "Write eigenvalue equation", "Matrix dimensions: (m×n)×(n×k)=?", "Centrifuge example — 3 principal components meaning"],
        ["Listed all 6 PCA steps from notes", "Did toy PCA by hand", "Watched StatQuest PCA videos", "Know centrifuge example", "Can explain 'reducing columns'"],
        [yt("FgakZw6K1QQ", "StatQuest — PCA Step-by-Step"), yt("HMOI_lkzW08", "StatQuest — PCA Main Ideas in 5 Minutes"), yt("_UVHneBUBW0", "StatQuest — PCA Full Walkthrough")],
        [res("Eigenvalues/Eigenvectors — 3Blue1Brown", "https://www.3blue1brown.com/lessons/eigenvalues", "doc")],
        55),
       task("d3-b1-t2", 3, 1, "06:30–08:00", "PCA Application — Vibration Monitoring Centrifuge", "🔬", "Surrogate",
        "Prof's PCA example (notes p.6): Vibration monitoring in centrifuge — 20 vibration features → PCA reduces to few principal components. PCA1 = overall vibration energy. PCA2 = imbalance or misalignment. PCA3 = bearing-related vibration patterns. This is condition monitoring for predictive maintenance — connects directly to your antenna RUL project (both are prognostics). Face recognition PCA example from lecture shows PCA works outside engineering too. Key exam answer: PCA is UNSUPERVISED — no labels needed.",
        "Write parallel between centrifuge PCA and antenna RUL: both reduce complex sensor data to actionable health indicators. Could you apply PCA to vibration data from antenna mounting brackets? Yes — extract dominant failure modes. Practice 30-second PCA explanation.",
        ["Centrifuge example — 3 PC meanings", "Is PCA supervised or unsupervised?", "How does PCA connect to your project?", "Face recognition PCA — why it works", "When to use PCA vs full model?"],
        ["Explained centrifuge PCA example", "Connected PCA to prognostics/RUL", "Know unsupervised property", "Practiced 30-sec PCA explanation", "Compared PCA to DoE (different purposes)"],
        [yt("FgakZw6K1QQ", "StatQuest — PCA Step-by-Step")],
        [res("Jardine et al. 2006 — Machinery Diagnostics Review", "https://doi.org/10.1016/j.ymssp.2005.09.012", "paper")],
        50)]),
    block(2, "08:00–11:00", "📡 Antenna RUL Project — Physics & Formula",
      [task("d3-b2-t1", 3, 2, "08:00–09:30", "Project Story — Drone Pipeline to Digital Twin", "📡", "Project",
        "YOUR PROJECT NARRATIVE (must be fluent): Industrial context — drone-based 2D imagery → 3D photogrammetric reconstruction of telecom towers (USA telecom client, ~€220K contract). Drone gives GEOMETRY (as-built twin). Your notebook adds PHYSICS — predictive RUL model = true digital twin. Module: Modeling, Simulation and Digital Twin, Prof. Dr. Adele Nasti. Objective: predict Remaining Useful Life of 5G/6G telecom tower antenna under wind speed and operating temperature using DoE methodology (HEEDS-style MDAO). Value: predictive maintenance, fewer climber visits, reduced outages, lower OPEX.",
        "Practice 2-minute project pitch WITHOUT slides. Structure: Problem → Approach → Results → Value. Mention drone pipeline FIRST (breadth), then RUL model (depth). Prepare answer: 'What is YOUR creative contribution?' → Combined real industrial geometry pipeline with original physics-based RUL model and full DoE analysis.",
        ["2-minute project pitch memorised", "What does drone pipeline provide?", "What does RUL model add?", "Creative contribution — your answer", "Business value in 3 bullet points"],
        ["Practiced 2-min pitch aloud", "Know industrial context numbers", "Clear problem→approach→results flow", "Prepared creativity answer", "Read full notebook intro cell"],
        [yt("9UpMeDO0A04", "Digital Twin Predictive Maintenance Context")],
        [res("Liu et al. 2021 — UAV Photogrammetry for Telecom Towers", "https://doi.org/10.1016/j.autcon.2021.103780", "paper"), res("Your Notebook", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb", "tool"), res("Your Presentation PPTX", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.pptx", "doc")],
        55),
       task("d3-b2-t2", 3, 2, "09:30–11:00", "RUL Formula — Derive & Defend Every Term", "🧮", "Project",
        "RUL (days) = L_nom / (f_wind × f_temp × H_day). L_nom = 175,200 hours ≈ 20 years nominal antenna life. f_wind(v) = (v/5)^1.6 — wind fatigue accelerator, baseline 1.0 at v=5 m/s, exponent 1.6 from drag-fatigue scaling. f_temp(T) = 2^((T-20)/15) — Arrhenius thermal aging, rate doubles every 15°C, baseline 1.0 at 20°C. H_day = 24 (antennas operate 24/7). SANITY CHECKS: (5m/s, 20°C)→7300 days=20yr. (15m/s, 35°C)→629 days=1.7yr. (35m/s, 65°C)→41 days. Prof will ask: 'Why exponent 1.6?' → drag force scales ~v², fatigue damage accumulates nonlinearly. 'Why Arrhenius?' → standard thermal degradation model for electronics.",
        "Derive RUL formula on blank paper from memory. Calculate all 3 sanity-check values by hand (no calculator first, then verify). Write defence for each parameter choice. Prepare: 'What would you calibrate with field data?' → exponent 1.6, doubling temperature 15°C, nominal life 175200h.",
        ["Write full RUL formula from memory", "Calculate RUL at (5, 20) by hand", "Calculate RUL at (35, 65) by hand", "Why exponent 1.6?", "Why Arrhenius with 15°C doubling?"],
        ["Derived formula on paper", "Hand-calculated 3 sanity checks", "Can defend every parameter", "Know calibration candidates", "No calculator needed for (5,20)"],
        [],
        [res("Jardine — RUL Prognostics Review", "https://doi.org/10.1016/j.ymssp.2005.09.012", "paper"), res("Your Notebook Cell 4", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb", "tool")],
        60)]),
    block(3, "11:00–14:00", "📈 DoE Results — Sensitivity, Pareto, Operating Envelope",
      [task("d3-b3-t1", 3, 3, "11:00–12:30", "Full Factorial DoE — 40 Runs & Design Matrix", "📋", "DoE",
        "DoE setup: 4 wind levels [5, 15, 25, 35] m/s × 10 temperature levels [20, 25, ..., 65]°C = 40 design points. This is FULL FACTORIAL (all combinations). Design matrix columns: wind_ms, temp_C, rul_days, rul_years. Baseline: (5, 20)→7300 days = 20 years exactly (validates model). Worst case: (35, 65)→41 days ≈ 0.1 years. Prof may ask: 'Why 4 wind levels but 10 temperature levels?' → Temperature has finer resolution because Arrhenius is exponential — small T changes have large RUL impact at high temps.",
        "Recreate the design matrix header and first 5 rows from memory. Explain why 40 runs is manageable (analytical model, not FEA). Compare to Prof's injection molding example (3 inputs, multiple outputs).",
        ["How many design points? Why?", "Wind levels and temp levels — list them", "Baseline result at (5, 20)?", "Worst case at (35, 65)?", "Why more temp levels than wind levels?"],
        ["Know 40-run design matrix", "Listed all factor levels", "Memorised baseline and worst case", "Can justify full factorial", "Compared to injection molding DoE"],
        [yt("_Rgue-7KDww", "DoE Design Matrix — JMP"), yt("9x9LYvErnwk", "DoE on Simulation Models")],
        [res("Montgomery DoE Textbook", "https://www.wiley.com/en-us/Design+and+Analysis+of+Experiments%2C+9th+Edition-p-9781119493918", "doc")],
        50),
       task("d3-b3-t2", 3, 3, "12:30–14:00", "Sensitivity, Pareto & Operating Envelope", "🗺️", "Project",
        "Sensitivity method: hold temp at midpoint 42.5°C, sweep wind 5→35 m/s → ΔRUL_wind. Hold wind at midpoint 20 m/s, sweep temp 20→65°C → ΔRUL_temp. Result: wind impact ≈ 3.5× temperature impact. Pareto chart visualises this — wind bar much taller. Operating envelope: contour plot of RUL in years; recommend wind≤12 m/s AND temp≤30°C for RUL>10 years (star marker on plot). Key conclusion for presentation: WIND SPEED is dominant degradation factor — counterintuitive because engineers often focus on temperature for electronics.",
        "Redraw Pareto bar chart from memory with approximate values. Mark operating envelope safe zone. Prepare 30-second 'key findings' summary: (1) RUL prediction across design space, (2) wind dominant, (3) safe operating region defined.",
        ["What is ΔRUL_wind (approx)?", "What is ΔRUL_temp (approx)?", "Wind/temp ratio?", "Operating envelope recommendation?", "Why is wind dominant counterintuitive?"],
        ["Redrew Pareto chart from memory", "Know operating envelope limits", "Memorised 3 key findings", "Can explain wind dominance", "Ran notebook cells 12-16"],
        [yt("HvF_3Rok8RY", "HEEDS — Response Surface & Optimization")],
        [res("Your Notebook Cells 12-16", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.ipynb", "tool")],
        55)]),
    block(4, "14:00–17:00", "🎤 Presentation Structure & Literature",
      [task("d3-b4-t1", 3, 4, "14:00–15:30", "10-Minute Presentation — Slide-by-Slide Script", "🎤", "Project",
        "Exam format: 10-15 min presentation + 10 min Q&A on ALL course topics. Criteria: technical understanding, depth/breadth, creativity, literature review, presentation skills. Suggested slide flow: (1) Title + your name/matric, (2) Problem — telecom tower maintenance cost/safety, (3) Industrial context — drone pipeline, (4) Digital twin framework — as-built + as-used, (5) RUL physics model + formula, (6) DoE setup 40 runs, (7) Results — RUL curves, (8) Sensitivity/Pareto — wind dominant, (9) Operating envelope, (10) Conclusions + future work (sensor integration, ML, FEA validation), (11) References. Manage time: ~1 min/slide.",
        "Open your PPTX. Time yourself presenting. Cut anything over 12 minutes. For each slide write 3 bullet speaker notes. Practice transitions: 'Now that we've defined the model, let me show the DoE approach...'",
        ["Present all slides in ≤12 minutes", "Speaker notes for each slide", "References slide with 5+ citations", "Future work slide honest limitations", "Demo ready: show notebook live or screenshots"],
        ["Timed presentation ≤12 min", "Speaker notes written", "References slide complete", "Practiced transitions", "Live demo or screenshots ready"],
        [yt("9CcbYQ5QA70", "Rolls-Royce — Example of Technical Presentation Style")],
        [res("Exam Guidelines PDF", "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Exam_Guidelines.pdf", "doc"), res("Your PPTX", "file:///Users/msv/Desktop/Desktop%20Wizzz/digital%20twin1/DigitalTwin_Antenna_RUL.pptx", "doc")],
        55),
       task("d3-b4-t2", 3, 4, "15:30–17:00", "References & Literature — Know Every Citation", "📚", "Project",
        "Your notebook references (know all 9): (1) AIAA 2020 Digital Twin Definition & Value, (2) Grieves & Vickers 2017 Springer, (3) Tao et al. 2019 IEEE, (4) Montgomery 2017 DoE textbook, (5) Jardine 2006 prognostics review, (6) Liu 2021 UAV photogrammetry telecom, (7) Kapteyn 2021 Nature Computational Science, (8) ISO/IEC 30173:2023, (9) Siemens HEEDS 2024. Prof tests literature review — be able to say WHAT each reference contributed in one sentence.",
        "For each of 9 references write: Author, Year, One-sentence contribution. Example: 'Montgomery 2017 — standard reference for Design of Experiments methodology used in our 40-run factorial study.' Practice: 'Why did you cite Kapteyn 2021?' → Probabilistic graphical model foundation for scalable digital twins.",
        ["Name all 9 references", "One-sentence contribution for each", "Which ref supports DoE choice?", "Which ref supports digital twin definition?", "Which ref supports prognostics/RUL?"],
        ["Listed all 9 references from memory", "One-sentence contribution for each", "Can justify each citation", "No fake references", "Read AIAA paper executive summary"],
        [],
        [res("AIAA 2020 Position Paper", AIAA, "paper"), res("Kapteyn 2021 — Nature Comp Sci", "https://doi.org/10.1038/s43588-021-00119-1", "paper"), res("ISO/IEC 30173:2023", "https://www.iso.org/standard/77808.html", "doc")],
        50)]),
    block(5, "17:00–20:00", "❓ Q&A Trap Questions — Full Course Coverage",
      [task("d3-b5-t1", 3, 5, "17:00–18:30", "25 Professor Trap Questions — Perfect Answers", "❓", "ALL",
        "Prepare perfect answers for: (1) What is digital twin? (2) V vs V? (3) Model coupling? (4) Full factorial DoE? (5) HEEDS purpose? (6) Pareto chart? (7) Global vs local min? (8) Surrogate model? (9) PCA steps? (10) Monte Carlo? (11) Fidelity vs accuracy? (12) As-designed/built/used? (13) Process automation? (14) Pugh matrix? (15) Mesh convergence? (16) Agile? (17) Dominant factor in your project? (18) RUL formula? (19) Why not FEA? (20) Creative contribution? (21) Calibration limitations? (22) TRL of project? (23) Functional modelling? (24) P-diagram noise factors? (25) Does DT replace testing?",
        "Write perfect 2-3 sentence answer for each of 25 questions. No bullet fragments — complete sentences only. Quiz yourself random order. Any answer that takes >30 seconds to start = rewrite.",
        ["Written perfect answer for Q1-13", "Written perfect answer for Q14-25", "Random-order self-quiz passed", "Each answer ≤3 sentences", "No hesitation on any question"],
        ["25 perfect answers written", "Random quiz passed", "Practiced aloud", "Fixed all weak answers", "Ready for 10-min Q&A"],
        [yt("HvF_3Rok8RY", "HEEDS — Quick Review"), yt("FgakZw6K1QQ", "PCA — Quick Review"), yt("9CcbYQ5QA70", "Digital Twin — Quick Review")],
        [res("Handwritten Class Notes Photos", "file:///Users/msv/Digital%20twin/", "doc")],
        60),
       task("d3-b5-t2", 3, 5, "18:30–20:00", "Complementary Topics — Motorcycle, HVAC, Injection Molding", "🔗", "ALL",
        "Prof asks complementary questions beyond your presentation. Know these cold from class notes: Motorcycle traction FFD (4 sections + feedback loop). HVAC coupled models (occupancy→heat→cooling→energy). Injection molding DoE (temp, pressure, cooling time → weight, deviation, surface, cycle time). Logistics optimisation (time+fuel, routes, constraints). Line-on-line interference → almost no wear. Smart building digital twin. Secondary air system seals (Prof's Rolls-Royce paper). For each: 2-sentence summary ready.",
        "Write 2-sentence summary for each complementary example. Connect at least 2 back to your antenna project. Example: 'Injection molding DoE parallels our antenna study — both use factorial design to map process inputs to quality/life outputs.'",
        ["2-sentence summary: motorcycle FFD", "2-sentence summary: HVAC coupling", "2-sentence summary: injection molding DoE", "2-sentence summary: logistics optimisation", "Connect 2 examples to antenna project"],
        ["All complementary examples summarised", "Connected 2+ to antenna project", "Reviewed handwritten notes photos", "Know seal design paper context", "No surprises in complementary Q&A"],
        [yt("ObGhB9CCHP8", "Siemens — Smart Building Digital Twin")],
        [res("Class Notes Photo 1", "file:///Users/msv/Digital%20twin/PHOTO-2026-04-27-12-02-20%207.jpg", "doc"), res("Prof Nasti ASME Seal Paper", "https://asmedigitalcollection.asme.org/GT/proceedings-abstract/GT2020/84188/V07CT14A023/1095072", "paper")],
        50)]),
    block(6, "20:00–23:00", "🏆 Final Boss — Full Mock Exam",
      [task("d3-b6-t1", 3, 6, "20:00–21:30", "Full Mock Exam — 15 min Present + 10 min Q&A", "🏆", "ALL",
        "Simulate the real exam: Set timer 15 min. Present full slide deck aloud. Immediately follow with 10 min Q&A — have someone quiz you OR use random question list from d3-b5-t1. Grade yourself: Did you finish in time? Any typos? Did you demonstrate breadth (drone+DoE+lifecycle) AND depth (formula derivation)? Did you answer Q&A with complete sentences?",
        "Record full mock exam on phone. Watch back. Note every 'um', every vague answer, every time you looked unsure. Fix those specific gaps. Re-run mock until clean.",
        ["15-min presentation completed in time", "10-min Q&A completed", "Self-graded against exam criteria", "Identified and fixed weak points", "Recording reviewed"],
        ["Full mock exam recorded", "Reviewed recording", "Fixed all weak points", "Second mock exam passed", "Confident for real exam"],
        [yt("9CcbYQ5QA70", "Technical Presentation Inspiration — Rolls-Royce")],
        [res("Exam Guidelines", "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Exam_Guidelines.pdf", "doc")],
        65),
       task("d3-b6-t2", 3, 6, "21:30–23:00", "Final Review — Handwritten Notes + Rest", "📖", "ALL",
        "Last pass through ALL handwritten note photos in order (p.1→p.8). For each page, close the photo and write 5 keywords from memory. Then sleep — memory consolidation is real. You have 36 tasks, 18 hours/day × 3 days, every definition from Prof. Nasti's lectures, your full antenna project, and verified YouTube links. Trust the prep.",
        "Flip through all 9 handwritten note photos. Write 5 keywords per page from memory. Set out presentation clothes/device. Charge laptop. Notebook runs offline. You are ready.",
        ["5 keywords from each of 9 note pages", "Presentation device charged", "Notebook runs without internet", "PPTX opens correctly", "Get proper sleep before exam"],
        ["Reviewed all handwritten notes", "Keywords written from memory", "Tech check complete", "Confident and rested", "Last attempt — you are ready"],
        [yt("9CcbYQ5QA70", "You've got this — Intelligent Engine"), yt("HvF_3Rok8RY", "HEEDS — Final confidence boost")],
        [res("All Class Note Photos", "file:///Users/msv/Digital%20twin/", "doc"), res("Prof Nasti Lecture PDF", "file:///Users/msv/Downloads/OneDrive_1_6-8-2026/DigitalTwin_Lectures_ProfAdeleNasti.pdf", "doc")],
        50)]),
  ]
}
emit_day("day3", day3)
print("Done — total tasks:", sum(len(b["tasks"]) for d in [day1,day2,day3] for b in d["blocks"]))
